### ISSUE TITLE
pretty-format plugin not found

### ISSUE THREAD

**Issue by mujuni88** [styled-components/jest-styled-components#1]
```
  Test suite failed to run

    Cannot find module 'pretty-format/build/plugins/ReactTestComponent' from 'serializer.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/jest-styled-components/src/serializer.js:2:25)
      at Object.<anonymous> (node_modules/jest-styled-components/src/index.js:2:20)
```

**Comment by mujuni88** [comment]
After I downloaded the pretty-format plugin, I get the following error:

TypeError: expect.addSnapshotSerializer is not a function

      at Object.<anonymous> (src/components/molecules/CommUserContactHeader/__tests__/index.test.js:8:304)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by MicheleBertoli** [comment]
Hello @mujuni88, which version of Jest are you using?

**Comment by mujuni88** [comment]
"jest": "17.0.2",
"jest-styled-components": "^0.1.1"

**Comment by mujuni88** [comment]
I'm also using enzyme-t-json serializer.

**Comment by MicheleBertoli** [comment]
Oh I see, the `addSnapshotSerializer` function has been introduced in [Jest 19](http://facebook.github.io/jest/blog/2017/02/21/jest-19-immersive-watch-mode-test-platform-improvements.html#expect-improvements).

**Comment by MicheleBertoli** [comment]
Did you change the `testEnvironment`?
See the [README](https://github.com/styled-components/jest-styled-components#usage).

**Comment by mujuni88** [comment]
That did it however, i’m getting a big json object instead of rendered html elements.

**Comment by mujuni88** [comment]
My tests look like the following:
```
beforeEach(() => {
    wrapper = shallow(
      <CallDialog
        contacts={contacts}
        subject='Hello this is the subject'
        body='Hello this is the body'
      />
    )
  })
  it('should match snapshot', () => {
    expect(wrapper).toMatchStyledComponentsSnapshot()
  })
```

**Comment by MicheleBertoli** [comment]
That's because you are passing the Enzyme wrapper to Jest.
You should either use the `react-test-renderer`, or `enzyme-to-json`.

**Comment by MicheleBertoli** [comment]
That's because you are passing the Enzyme wrapper to Jest.
You should either use the `react-test-renderer` or `enzyme-to-json`.

**Comment by mujuni88** [comment]
The above test is using enzyme-to-json serializer which is automatically applied by setting it inside jest configuration `snapshotSerializers`.

**Comment by MicheleBertoli** [comment]
Please use the `toJSON` function from `enzyme-to-json` for now.
I'll investigate the problem in a different issue.

**Comment by MicheleBertoli** [comment]
Please use the `toJSON` function from `enzyme-to-json`.

**Comment by MicheleBertoli** [comment]
Solution 1:

```js
import enzymeToJsonSerializer from 'enzyme-to-json/serializer'
import { serializer as styledComponentsSerializer } from 'jest-styled-components'

expect.addSnapshotSerializer(styledComponentsSerializer)
expect.addSnapshotSerializer(enzymeToJsonSerializer)
```

Solution 2:

```js
import toJson from 'enzyme-to-json'

// ...

expect(toJson(wrapper)).toMatchStyledComponentsSnapshot()
```

**Comment by MicheleBertoli** [comment]
With the current version ([v1.1.0](https://github.com/styled-components/jest-styled-components/releases/tag/v1.1.0)) you can use:
```js
"snapshotSerializers": [
  "enzyme-to-json/serializer"
]
```

**Comment by mujuni88** [comment]
Will try it out and let you know. Thanks for your work.
