### ISSUE TITLE
"Property not found" when testing for styleRules applied by modifier

### ISSUE THREAD

**Issue by doque** [styled-components/jest-styled-components#104]
Hi,

I'm unable to test for style rules that are applied using modifiers.

This problem occurs when using `mount` as well as `shallow`. It is not rule-specific, if I switch `border-radius` with `background-color` it doesn't solve the problem.

```js
const colors = {
  readonly: 'lightgray'
};

const readonlyStyles = `
  border-radius: 3px;

  &:read-only {
    background-color: ${colors.readonly};
  }
`;

const InputField = styled.input`
  ${readonlyStyles};
  height: 20px;
`;

// This test fails
test('renders correctly with readOnly prop', () => {
  const wrapper = shallow(<InputField readOnly />);
  expect(wrapper).toHaveStyleRule('background-color', colors.readonly);
});

// This test passes
test('renders correct border', () => {
  const wrapper = shallow(<InputField readOnly />);
  expect(wrapper).toHaveStyleRule('border-radius', '3px');
});

```

I've set up a sample repository like in #77, I hope it helps: https://github.com/doque/jest-styled-components-properties/tree/bug/disabled

**Comment by MicheleBertoli** [comment]
Hello @doque, thanks for opening the issue and creating a sample repository - that helps a lot.
In order to find the style rules within a modifier you need to specify it as the third [option](https://github.com/styled-components/jest-styled-components#tohavestylerule) of the matcher, as follows:

```js
expect(wrapper).toHaveStyleRule('background-color', colors.readonly, {
  modifier: ':read-only',
})
```

I hope this helps!

**Comment by doque** [comment]
Awesome, thank you!  👍

**Comment by leotm** [comment]
Just came across this and checking regarding 2019 implementation, `toHaveStyleRule` requires mounting right as opposed to shallow?
