### ISSUE TITLE
toHaveStyleRule not working under preact

### ISSUE THREAD

**Issue by jspath** [styled-components/jest-styled-components#109]
Does toHaveStyleRule work under preact?

```
import React from 'react'
import styled from 'styled-components'
import render from 'preact-render-to-json'
import 'jest-styled-components'

const Button = styled.button`
  color: red;
`;

test('it works', () => {
  const tree = render(<Button />);
  expect(tree).toMatchSnapshot()
  expect(tree).toHaveStyleRule('color', 'red')
})
```

The snapshot looks like:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`it works 1`] = `
.c0 {
  color: red;
}

<button
  class="c0"
  ref={undefined}
/>
`;
```

But I get `Property not found "color"` on the toHaveStyleRule matcher.

It's not clear to me if toHaveStyleRule is supposed to work in preact or not.

**Comment by MicheleBertoli** [comment]
Fixed in [v4.10.0](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#4100---2018-01-14).
Thank you very much, @jspath.
