### ISSUE TITLE
Classnames beginning with hyphens

### ISSUE THREAD

**Issue by joetidee** [styled-components/jest-styled-components#111]
I have just installed v1.4.0 and noticed that some of the classnames generated in my Jest snapshots begin with hyphens - this is the first time I have seen this. Is this correct?

Here is an example of the output:
<strong classname="c7 -strong c8">

**Comment by MicheleBertoli** [comment]
Hello @joetidee, thanks for opening the issue.
Would you mind proving more information and a minimal repro example?

**Comment by MicheleBertoli** [comment]
Please reopen this if you are able to provide more information.
Thank you very much!
