### ISSUE TITLE
jest-styled-components peer dependency

### ISSUE THREAD

**Issue by gscottolson** [styled-components/jest-styled-components#121]
Just wondering if there is an ETA for the release that uses the styled-components peer dependency of ^3.0.2…

https://github.com/styled-components/jest-styled-components/blob/0f74941c68d68604e2202842bc2b3e5e1e374a64/package.json#L54

**Comment by MicheleBertoli** [comment]
Hello @gscottolson, you can install the current master version with: 
`yarn add jest-styled-components@next`

I'm going to publish a new release very soon.

**Comment by MicheleBertoli** [comment]
Thanks for your comment, @hjemmel.
Styled Components v4 is [not fully supported](https://github.com/styled-components/jest-styled-components/issues/191) yet (especially with Enzyme).
