### ISSUE TITLE
Doesn't seem to work with 3.2.0 

### ISSUE THREAD

**Issue by caffodian** [styled-components/jest-styled-components#122]
I'm guessing this is due to the StyleSheet changes, but I don't know enough about how all the internals work.  My snapshots are back to using hashed names rather than the nice c1, c2, etc.

Thanks for the project, and sorry if this is a dupe issue.

**Comment by MicheleBertoli** [comment]
Hello @caffodian, thanks for opening this issue.

I just updated this repo to `styled-components` v3.2.0 and it seems there are no issues (except a few vendor rules): please check a54ca4b73f3a0f1038d965acc9ff6e2b4e33a9dc.
Also, we now have [integration tests](https://github.com/styled-components/styled-components/blob/master/integration-test/__snapshots__/jest-styled-components.test.js.snap#L4) and they are [green](https://travis-ci.org/styled-components/styled-components/builds/349439255).

Would you mind checking if there's something wrong with your setup?
In case you manage to provide a non-working example, I'll be happy to help.
