### ISSUE TITLE
Only works with a shared instance of styled-components

### ISSUE THREAD

**Issue by dfrankland** [styled-components/jest-styled-components#125]
I work on a [Lerna](https://github.com/lerna/lerna) monorepo of component packages that contains multiple instances of [`styled-components`](https://github.com/styled-components/styled-components) and a global [Jest](https://github.com/facebook/jest/) [`setupTestFrameworkScriptFile`](https://facebook.github.io/jest/docs/en/configuration.html#setuptestframeworkscriptfile-string). Unless each package lists [`styled-components`](https://github.com/styled-components/styled-components) as a part of [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies), which will share an instance from the root `node_modules`, `jest-styled-components` won't work.

Tangentially related (fixes this warning): https://github.com/styled-components/styled-components/issues/1592

I think, at the very least, this should be added as a warning to the "Global installation" section of the [`README.md`](https://github.com/styled-components/jest-styled-components#global-installation). What do y'all think?

**Comment by kitten** [comment]
Wait, I didn’t realise you had multiple instances of styled-components.

This can lead to a lot of unexpected issues in an app, so is there any reason why you’re not letting lerna deduplicate it?

**Comment by dfrankland** [comment]
Each of the packages had the same version of `styled-components` which would be deduped by any app that installs multiple of the packages published from the monorepo. But, when using Jest, this loads them as separate instances due to each package having `styled-components` in its respective `node_modules`.

**Comment by MicheleBertoli** [comment]
Thank you very much, @dfrankland @kitten.
Do you mind submitting a PR which adds this information to the README, @dfrankland?

**Comment by dfrankland** [comment]
@MicheleBertoli cheers, I've just made a PR: #131.
