### ISSUE TITLE
Not all classnames are being converted into C0, C1, etc.

### ISSUE THREAD

**Issue by webbhead777** [styled-components/jest-styled-components#133]
When I run my tests locally using jest-styled-components the classnames are replaced with the shortened names and it matches the snapshot beautifully. But once I push to our CI for some reason the test prints the styled components hash for some classnames and shortened names for others. and out of order too: so a snapshot with `C8` ends up being `C0`, `C9` is `C1` etc. and it inevitably fails. Has anyone else experienced this issue? (I'm wondering if it has to do with a difference in OSX & Linux?)

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue @webbhead777.
I've never experienced anything similar, would you be able to provide an example?
