### ISSUE TITLE
property not found using styled-system

### ISSUE THREAD

**Issue by karolisgrinkevicius** [styled-components/jest-styled-components#134]
#### ./MyComponent.js
```jsx
import styled, { ThemeProvider } from 'styled-components';
import { theme } from 'styled-system';

export const StyledMyComponent = styled.span`
  color: ${theme('colors.primary')};
`;

const colors = {
  primary: '#000000',
};

export const MyComponent = props => (
  <ThemeProvider theme={{ colors }}>
    <StyledMyComponent>{props.children}</StyledMyComponent>
  </ThemeProvider>
);
```

#### ./MyComponent.spec.js
```jsx
import * as React from 'react';
import { shallow } from 'enzyme';
import { ThemeProvider } from 'styled-components';
import 'jest-styled-components';
import { MyComponent } from './MyComponent';

const colors = {
  primary: '#000000',
};

describe('<MyComponent />', () => {
  it('has primary colour', () => {
    const wrapper = shallow(
      <ThemeProvider theme={{ colors }}>
        <MyComponent />
      </ThemeProvider>,
    );
    expect(wrapper).toHaveStyleRule('color', '#000000');
  });
});
```

#### Expected result
👏🏻🍻

#### Actual result
🖕🏻👺

`Property not found: "fill"`

#### Dependencies
- `jest@22.4.3`
- `styled-components@3.2.5`
- `jest-styled-components@5.0.1`
- `styled-system@2.2.1`

#### Explanation
I've tried to use both `shallow` and `mount` from `enzyme` and got the same result.

**Comment by karolisgrinkevicius** [comment]
Thanks for you response @MicheleBertoli. In fact `styled-system` does not have exported member `themeGet`. So I'm pretty sure I'm using it correctly importing `theme` from `styled-system`. Also I have wrapped up parent component `<App />` with `ThemeProvider`. Should this be somehow set up in `jest` configuration? I could not find any useful documentation about setting up `jest` to be able to use themes within unit tests.

**Comment by MicheleBertoli** [comment]
> In fact styled-system does not have exported member themeGet. So I'm pretty sure I'm using it correctly importing theme from styled-system.

I'm not familiar with `styled-system` but the documented method is [themeGet](https://github.com/jxnblk/styled-system#themeget), which is aliased as [theme](https://github.com/jxnblk/styled-system/blob/master/src/index.js#L90).

> Also I have wrapped up parent component <App /> with ThemeProvider.

Oh, I can't see this in your snippet, would you be able to provide a complete non-working example?

> Should this be somehow set up in jest configuration? I could not find any useful documentation about setting up jest to be able to use themes within unit tests.

[Here](https://github.com/styled-components/jest-styled-components#theming)'s what we have around themes, I hope it helps.

Thank you very much!

**Comment by MicheleBertoli** [comment]
Thank you very much for modifying the example, @karolisgrinkevicius.
However, you forgot to use the `shallowWithTheme` utility described in the [README](https://github.com/styled-components/jest-styled-components#theming).

I created an example with all the renderers, which I hope is going to answer all of your questions:

```js
const colors = {
  primary: '#000000',
}

const MyComponent = styled.span`
  color: ${theme('colors.primary')};
`

// Renderer

test('it works with renderer', () => {
  const tree = renderer
    .create(
      <ThemeProvider theme={{ colors }}>
        <MyComponent />
      </ThemeProvider>
    )
    .toJSON()
  expect(tree).toHaveStyleRule('color', colors.primary)
})

// Shallow

const shallowWithTheme = (tree, theme) => {
  const context = shallow(<ThemeProvider theme={theme} />)
    .instance()
    .getChildContext()
  return shallow(tree, { context })
}

test('it works with shallow', () => {
  const wrapper = shallowWithTheme(<MyComponent />, { colors })
  expect(wrapper).toHaveStyleRule('color', colors.primary)
})

// Mount

test('it works with mount', () => {
  const wrapper = mount(
    <ThemeProvider theme={{ colors }}>
      <MyComponent />
    </ThemeProvider>
  )
  expect(wrapper).toHaveStyleRule('color', colors.primary)
})
```

**Comment by karolisgrinkevicius** [comment]
Actually I have ended up mocking `theme` for `styled-system` which works really well.

In `jest.setup.js` I have the following:
```js
import * as styledSystem from 'styled-system';
jest.mock('styled-system');

styledSystem.theme = jest.fn().mockImplementation(k => k); // return key passed to theme
```

Then I just test that actual key has been passed correctly to the `theme`:

```js
// component
export const Component = styled.span`
  color: theme('colors.black'))};
`;

// unit test
it('fills with black colour', () => {
  const wrapper = shallow(<Component />);
  expect(wrapper).toHaveStyleRule('color', 'colors.black');
});
```
Thanks @MicheleBertoli.

**Comment by FDiskas** [comment]
Non working live example: https://codesandbox.io/s/4qvn61wjlx?expanddevtools=1&module=%2Fsrc%2FMyComponent.spec.js
:musical_score:

**Comment by MicheleBertoli** [comment]
You should use:

```js
import { StyledMyComponent } from "./MyComponent";
```

instead of:

```js
import { MyComponent } from "./MyComponent";
```

I hope this helps.
