### ISSUE TITLE
Different identifiers other that c0, c1, etc

### ISSUE THREAD

**Issue by miketamis** [styled-components/jest-styled-components#142]
The current pattern of c0, c1, c2, means that if I add another styled component my snapshot diffs become a mess, because they end up having all the numbers change.

One suggestion would be to use the react displayName to help make the class. I have created a quick example of this:

[Commit](https://github.com/miketamis/jest-styled-components/commit/956b1a09dee6914b27946ef6629bf7dd7964cfe5)

[Example of a Snapshot](https://github.com/miketamis/jest-styled-components/commit/956b1a09dee6914b27946ef6629bf7dd7964cfe5#diff-6c5f4a81addec1ba29a9b374ffdf8bf1)

**Comment by miketamis** [comment]
this is also means that if you want to force a name for the class you can do
```js
  const ANamed = styled.div`
    color: green;
  `
  ANamed.displayName = 'ANamed'
```

which would result in this snap

```html
.ANamed-1 {
  color: red;
}

<ANamed>
  <div
    className="ANamed-1"
  />
</ANamed>
```

**Comment by MicheleBertoli** [comment]
Thank you very much @miketamis for opening the issue and proposing a solution.
I [mentioned](https://github.com/styled-components/jest-styled-components/pull/31#issuecomment-311495268) the problem you are referring to in the comments of the release v4 (where we started applying the `c0..cN` approach).

Using the `displayName` seems like a good idea but I see a few problems:
- [it seems to work for Enzyme only](https://github.com/styled-components/jest-styled-components/compare/master...miketamis:master#diff-6c5f4a81addec1ba29a9b374ffdf8bf1R405).
- I'm not entirely sure it provides a better DX.

Suppose we start with the following tree:

```js
const Red = styled.div`
  color: red;
`

const Green = styled.div`
  color: green;
`

const tree = (
  <Red>
    <Green />
  </Red>
)
```

And then we add a new component that wraps the existing ones (the worst case scenario of the `c0..cN` approach):

```js
const Red = styled.div`
  color: red;
`

const Green = styled.div`
  color: green;
`

const Blue = styled.div`
  color: blue;
`

const tree = (
  <Blue>
    <Red>
      <Green />
    </Red>
  </Blue>
)
```

The resulting diff of the current implementation looks like this:

```diff
- Snapshot
+ Received

- .c0 {
+ .c1 {
    color: red;
  }

- .c1 {
+ .c2 {
    color: green;
  }

+ .c0 {
+   color: blue;
+ }
+
  <div
    className="c0"
  >
    <div
      className="c1"
-   />
+   >
+     <div
+       className="c2"
+     />
+   </div>
  </div>
```

While, the diff of your proposed implementation looks like this:

```diff
- Snapshot
+ Received

  .Green-1 {
    color: green;
  }

- <Red>
+ .Blue-1 {
+   color: blue;
+ }
+
+ <Blue>
    <div
-     className="Red-1"
+     className="Blue-1"
    >
-     <Green>
+     <Red>
        <div
-         className="Green-1"
-       />
-     </Green>
+         className="Red-1"
+       >
+         <Green>
+           <div
+             className="Green-1"
+           />
+         </Green>
+       </div>
+     </Red>
    </div>
- </Red>
+ </Blue>
```

I would argue that the first one is cleaner, what do you think?

**Comment by MicheleBertoli** [comment]
100% agree with you @miketamis, there's no perfect solution.
We tried out a few different solutions and we chose what we think is the best trade-off (for the most common use-cases).

I'm more than happy to change approach, but this doesn't seem optimal, and it doesn't work with the `react-test-renderer` unfortunately.
I'm closing this for now but please keep on experimenting, and sharing your ideas.
