### ISSUE TITLE
Snapshot is missing css/styles when using shallow from enzyme

### ISSUE THREAD

**Issue by chhuang** [styled-components/jest-styled-components#145]
When I do:

```
import { shallow } from 'enzyme'

test('it works', () => {
  const wrapper = shallow(<Button />)
  expect(wrapper).toMatchSnapshot()
})
```

I only get:
```
exports[`Button renders correctly Renders correctly as a link 1`] = `<Button____Button />`;
```

It's fine if I use renderer from `react-test-renderer`:
```
const wrapper = renderer.create(<Button />).toJSON()
expect(wrapper).toMatchSnapshot()
```

**Comment by carloscheddar** [comment]
I'm experiencing this issue as well and managed to reproduce it on code sandbox. I added 2 test cases 1 for `enzyme` and another for `react-test-renderer`. You can see the difference in the snapshot results on the test output https://codesandbox.io/s/o5ko8vlp39.

**Comment by MicheleBertoli** [comment]
Thank you very much @carloscheddar for providing detailed repro code.

The reasons why there's no style in the first snapshot are:
- `Hello` is not a `styled-component`
- you are `shallow` rendering

That's the expected behaviour.

If you try using `mount` you'll see the styles in the snapshot.

**Comment by rjohnep** [comment]
Hi @MicheleBertoli 
I have a similar problem with snapshots. 
`react-test-renderer` generate right snapshots unlike `enzyme` 
```js
//react-test-renderer
.c0 {
  color: red;
}

<button
  className="c0"
/>


//****** VS ******//
//enzyme && enzyme-to-json
<StyledComponent
  forwardedComponent={
    Object {
      "$$typeof": Symbol(react.forward_ref),
      "attrs": Array [],
      "componentStyle": ComponentStyle {
        "componentId": "sc-bdVaJa",
        "isStatic": false,
        "rules": Array [
          "
  color: red;
",
        ],
      },
      "displayName": "styled.button",
      "foldedComponentIds": Array [],
      "render": [Function],
      "styledComponentId": "sc-bdVaJa",
      "target": "button",
      "toString": [Function],
      "warnTooManyClasses": [Function],
      "withComponent": [Function],
    }
  }
  forwardedRef={null}
/>
```
Can you check it?
In relation `mount` - no problem.
https://codesandbox.io/s/9jxq3j39yp?module=%2Fsrc%2Findex.test.js&previewwindow=tests

Regards

**Comment by MicheleBertoli** [comment]
Thanks for your comment, @rjohnep.
Styled Components v4 is [not fully supported](https://github.com/styled-components/jest-styled-components/issues/191) yet (especially with Enzyme).

**Comment by Jose-Bustamante** [comment]
Hi @MicheleBertoli is there any update when this could be fixed? 

This is how my snapshot looks like when using Shallow, I am not sure if I could be doing something wrong.  
Styled-components v: 4.1.1
`
<styles__StyledCartTotal>
    +   <styles__StyledCartTotalBody>
    +     <styles__OrderValue>
    +       <P>
    +         <Connect(branch(TranslationTextComponent))
    +           defaultMessage="Order value ex. VAT"
    +           id="checkout.orderTotalExclTax"
    +         />
    +       </P>
    +       <styles__Price>
              20
    +       </styles__Price>
    +     </styles__OrderValue>
    +   </styles__StyledCartTotalBody>
    + </styles__StyledCartTotal>
`
`
import renderer from 'react-test-renderer';
`
works fine, also enzyme mount, is just a bit annoying to mock the store the whole time 😣
