### ISSUE TITLE
CSS Properties are duplicated in snapshot when using styled(...) syntax.

### ISSUE THREAD

**Issue by tylerferguson** [styled-components/jest-styled-components#15]
Hi again.

This time I think I have a real bug. Promise :).

When using `styled(...)` to override the styles on a component the CSS properties overridden are duplicated in the snapshot produced. The example below should illustrate this:
```js
/**
 * @jest-environment node
 */

import React from 'react'
import styled from 'styled-components'
import renderer from 'react-test-renderer'
import { shallow } from 'enzyme'
import 'jest-styled-components';

const Button = styled.button`
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
`

const TomatoButton = styled(Button)`
  background: tomato;
`

test('enzyme', () => {
  const tree = shallow(
    <TomatoButton>
      Hello World!
    </TomatoButton>,
  )

  expect(tree).toMatchStyledComponentsSnapshot()
})

test('react-test-renderer', () => {
  const tree = renderer
    .create(
      <TomatoButton>
        Hello World!
      </TomatoButton>,
    )
    .toJSON()

  expect(tree).toMatchStyledComponentsSnapshot()
})
```

Produces the snapshots:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`enzyme 1`] = `
.jUiOOZ {
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  background: tomato;
}

<button
  className="jUiOOZ"
>
  Hello World!
</button>
`;

exports[`react-test-renderer 1`] = `
.jUiOOZ {
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  background: tomato;
}

<button
  className="jUiOOZ"
>
  Hello World!
</button>
`;
```

Note the duplication of the `background` property. It seems it's actually easy enough to follow and the latter property is the one that will actually be present on the class.

I'm starting to see if I can work out where this can be fixed now. 

Thanks!

Tyler

**Comment by MicheleBertoli** [comment]
Hello @tylerferguson, thanks for opening the issue.

It's interesting that you think there's a bug in the library, but this is how Styled Components work:

<img width="229" alt="screen shot 2017-05-08 at 9 49 55 pm" src="https://cloud.githubusercontent.com/assets/1308971/25824730/54ecb6bc-3438-11e7-8cae-072b7027751a.png">

However, the value snapshot testing provides is keeping track of how the state changes over time and that works even in this case.

**Comment by tylerferguson** [comment]
Hi @MicheleBertoli. Thanks for getting back to me. I understand that the latter property is what will be applied as per the CSS spec, but is that what a snapshot should show? Tracking how the styles change over time seems to be at odds with the idea of a 'snapshot' at a single point in time.

 It gets quite confusing with larger classes too and doesn't wholly represent what is actually rendered as I would expect a snapshot to. Though you may argue that it _is_ representative of what is actually rendered just not what you actually see ;). 

I think that if the idea of snapshot testing is for us to 'see' the component as it would be then jest-styled-components is slightly (only slightly!) broken, as a change to the `background` CSS property in `Button` would break my snapshot for `TomatoButton`. Do you think there's any merit in that argument?

**Comment by MicheleBertoli** [comment]
> [...] analyze how state changes over time.

This is the purpose of [Jest](https://facebook.github.io/jest/), which does it by taking snapshots.

I understand your confusion but I believe snapshots should represent what's rendered rather than what you see.

How would you expect the snapshot to be in the following scenario?
```js
const Button = styled.button`
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
`

const TomatoButton = styled(Button)`
  display: none;
`
```

In any case, feel free to experiment in this area and send a PR.
The goal of this package is making testing a delightful experience, and any new idea is welcome.

**Comment by tylerferguson** [comment]
> [...] analyze how state changes over time.

Isn't this referring to taking multiple snapshots and how that allows you to see how state changes over time? Take a snapshot, click a button, take another snapshot and so on. Certainly, I wouldn't expect to see a dropdown menu both display and hide its options in one snapshot! But in several snapshots I can see how it has changed over time.

> How would you expect the snapshot to be in the following scenario?

I would expect to see something like:

```
exports[`enzyme 1`] = `
.jUiOOZ {
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  display: none;
}

...
`;
```

However, if Button itself had a display property like so:
```js
const Button = styled.button`
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  display: inline-block;
`

const TomatoButton = styled(Button)`
  display: none;
`
```

I would personally expect to see a snapshot that looks like:

```
exports[`enzyme 1`] = `
.jUiOOZ {
  background: palevioletred;
  border-radius: 3px;
  border: none;
  color: white;
  display: none;
}

...
`;
```

Which is actually the same as the last snapshot and supports the idea that `TomatoButton`'s snapshot should not break just because someone added an irrelevant (to us anyway) `display: inline-block` to `Button`.

I do understand the point you are making however, in that there would be nothing to 'see' in the above example, so perhaps that's not the right measure of a snapshot. 

I think that the current output, while being a more accurate representation of what is happening with `styled-components`, is probably less helpful in testing than the alternative of keeping only the CSS properties that have been overridden.

Thanks for engaging in this discussion, it's been really helpful!

**Comment by MicheleBertoli** [comment]
For reference, snapshots track how the state change over time (= between different executions of the same test).

> being a more accurate representation of what is happening with styled-components

I guess this is the whole point of snapshots: you want to make sure your output doesn't change unexpectedly, which has nothing to do with what you see in the browser.

However, I'm curious to see what other people think about this.
Thanks you very much for spending time experimenting.
