### ISSUE TITLE
Upgrading Styled components to 3.3.3 breaks

### ISSUE THREAD

**Issue by albert-olive** [styled-components/jest-styled-components#150]
Hi, Upgrading to styled components at v3.3.3 breaks the snapshots:

![image](https://user-images.githubusercontent.com/27954280/41840469-1d8e6c7e-7866-11e8-94e6-669ff669a81d.png)

**Comment by MicheleBertoli** [comment]
Hello @albert-olive, thanks for opening this issue.

I installed SC v3.3.3 on this repo, and tests are green.
Also, we now have an integration test on the SC repo [which is green](https://travis-ci.org/styled-components/styled-components/builds/394690443?utm_source=github_status&utm_medium=notification).

Do you mind providing more information, and double-checking you didn't change anything else?
Which version of this packare are you using?

**Comment by albert-olive** [comment]
Hi,

I have greenkeeper installed and the only thing it did, in that branch, was to upgrade to v3.3.3 and it didn't pass the tests I have.

I'm using create react app. I have this versions:

```
"react": "16.4.0",
"react-dom": "16.4.0",
"jest-styled-components": "5.0.1"
"styled-components": "3.2.3",
```

![image](https://user-images.githubusercontent.com/27954280/41893233-550a17a6-791b-11e8-8e5d-daf71c526d3f.png)


Thanks

**Comment by MicheleBertoli** [comment]
I'm closing this because this repo [is using 3.3.3](https://github.com/styled-components/jest-styled-components/blob/master/yarn.lock#L6466) and the tests are green.
Feel free to reopen the issue if you are able to provide more information @albert-olive.
Thank you very much!
