### ISSUE TITLE
toHaveStyleRule cannot find nested CSS property when nested pseudo-class present.

### ISSUE THREAD

**Issue by joshualoehr** [styled-components/jest-styled-components#152]
Hi,

I spent a lot of time trying to track down this bug, and I'm not sure there will be an easy fix but I wanted to notify the maintainers and anyone else who experiences this.

Consider the following toy example:
```javascript
import React from 'react';
import styled, { css } from 'styled-components';
import 'jest-styled-components';

const Button = styled.button`
    color: 'red'

    .Toy-control {
      border-color: ${props => (props.error ? 'red' : 'green')}  

      &:focus {
        border-color: 1px solid blue
      }      
    }
`

class Toy extends React.Component {
    constructor(props) {
      super(props);      
    }

    render() {
        const {
            id,
            error,
            label
        } = this.props;
        return (
            <Button error={error !== ''}>
                {label} 
            </Button>
        );
    }
}

test('it works with provided error', () => {
    const tree = shallow(<Toy error={'some error'} />);
    expect(tree).toHaveStyleRule('border-color', 'red', {
      modifier: css`.Toy-control:focus`,  
    });
});
```

I'm trying to test the CSS logic for coloring the button border, but `toHaveStyleRule` throws a `Property not found: "border-color"` error. After some digging around in the source for `toHaveStyleRule`, I found that this is because the css parser gives the wrong selectors for the rule:

```
{ type: 'rule',
        selectors: [ 'border-color:red .iRRYKP .Select-control:focus' ],
        declarations: [ [Object] ],
        position: Position { start: [Object], end: [Object], source: undefined } }
```

As you can see, selectors includes `'border-color:red'` for some reason, and this causes that rule to be filtered out in `getRules`. I think this is a bug in the `css` npm dependency used for parsing, but it looks like [that package is no longer maintained](https://github.com/reworkcss/css/issues/109). 

I was able to work around this by changing the CSS to have the pseudo-class listed first, i.e.:
```javascript
const Button = styled.button`
    color: 'red'

    .Toy-control {
      &:focus {
        border-color: 1px solid blue
      } 
      border-color: ${props => (props.error ? 'red' : 'green')}  
    }
`
```

With that change, the css parsing works as expected and the test passes.

**Comment by MicheleBertoli** [comment]
Thank you very much @joshualoehr for opening this issue.

I can see a few problems with the snippet you posted:

**1- Shallow rendering**

You are using shallow rendering to test a nested component.
This doesn't render any styles for the child component.

```js
<styled.button
  error={true}
/>
```

**2- Semicolons**

The CSS generated from the `Button` component is actually invalid, as it doesn't have the semicolons.
I tried it in Codesandbox and it doesn't seem to work there too.

**3- Failing test**

Even fixing 1 and 2 wouldn't make the test pass, because it's checking for the wrong value (`red`).

---

Here's a working version (without changing the order of the style rules).

```js
const Button = styled.button`
  color: 'red';

  .Toy-control {
    border-color: ${props => (props.error ? 'red' : 'green')};

    &:focus {
      border-color: 1px solid blue;
    }
  }
`

class Toy extends React.Component {
  constructor(props) {
    super(props)
  }

  render() {
    const { id, error, label } = this.props
    return <Button error={error !== ''}>{label}</Button>
  }
}

test('it works with provided error', () => {
  const tree = mount(<Toy error={'some error'} />)
  expect(tree).toHaveStyleRule('border-color', '1px solid blue', {
    modifier: css`.Toy-control:focus`,
  })
})
```

I hope this helps.
