### ISSUE TITLE
toHaveStyleRule SyntaxError on test run 

### ISSUE THREAD

**Issue by tylerreckart** [styled-components/jest-styled-components#165]
I've been having quite the time getting tests to run on a styled component.

This is the error I'm currently facing when I try to run the test:
```
 FAIL  src/components/Link/__tests__/index.js
  ● Test suite failed to run

    .../node_modules/jest-styled-components/src/toHaveStyleRule.js:100
    const normalizeOptions = ({ modifier, ...options }) =>
                                          ^^^

    SyntaxError: Unexpected token ...
```

The environment is a simple CRA generated React app. I've tried updating my jest config for the test environment, but no dice.

I've also run into a number of errors that seemed to be due to an improper babel config, however I haven't been able to get past this issue for my test to even run. 

I'm leaning towards this being a babel configuration issue because the issue is with the spread syntax, but ¯\_(ツ)_/¯

#### .babelrc
```
{
  "plugins": [
    "transform-object-rest-spread"
  ],
  "presets": [
    [
      "env", {
        "targets": {
          "node": "current"
        }
      }
    ],
    "react"
  ]
}
```

**Comment by davidwilde** [comment]
I'm also running into this issue but only in my build environment. You closed this ticket, is it because you found a way to resolve this?

**Comment by davidwilde** [comment]
Discovered that this was due to my build server using a different version of node. I upgraded it to v10 as found in https://github.com/styled-components/jest-styled-components/issues/110#issuecomment-418476466 and the problem went away
