### ISSUE TITLE
TypeScript syntax error in v6.0.0 index.d.ts

### ISSUE THREAD

**Issue by elektronik2k5** [styled-components/jest-styled-components#167]
I believe there's a bug here:
https://github.com/styled-components/jest-styled-components/blob/17450d167b707177201f64359ea5f9d327b46394/src/index.d.ts#L3

In `typescript@3.0.1` (the only version I tested, but I don't think it is specific to 3), it is a syntax error:
```shell
Failed to compile.

/path/to/project/node_modules/jest-styled-components/src/index.d.ts
(3,51): Member 'Function' implicitly has an 'any' type.
```

I believe, though am not sure (otherwise I'd make a PR) the fix is as simple as:
```diff
-  sample?: string | RegExp | object | Array<any>, Function;
+  sample?: string | RegExp | object | Array<any> | Function;
```

@santino, is my assumption correct? I'm not familiar with asymmetric matchers yet.
@MicheleBertoli I can try to make a PR to test TS types as part of the test suite in order to prevent such omissions in the future. I've recently done something similar: https://github.com/caiogondim/fast-memoize.js/pull/69

**Comment by MicheleBertoli** [comment]
Thank you very much @elektronik2k5 for opening this issue.

In the Jest repo the `AsymmetricMatcher` is defined as an [Object](https://github.com/facebook/jest/blob/d3a6a7400a89b857a63d939fc5664ae8a2dfbbb2/types/Matchers.js#L45).
Unfortunately, I'm not familiar with TS but your suggested fix seems correct.

Also, it'd be awesome to test the TS types to prevent issues like this to happen again.
