### ISSUE TITLE
The styled-component and hoc function testing error

### ISSUE THREAD

**Issue by yuanlai** [styled-components/jest-styled-components#168]
I have a hoc function used for wrapping a animation for any component I want.

    import React from "react";
    import styled from "styled-components";
    
    import { fadeInUp, fadeOutDown } from "./animation";
    
    const FadeContainer = styled.div`
      animation: ${props =>
        props.routeAnimation === "fadeInUp"
          ? fadeInUp + " 250ms ease forwards"
          : props.routeAnimation === "fadeOutDown"
            ? fadeOutDown + " 200ms ease forwards"
            : ""};
    `;
    
    export const withFadeAnimation = Component => ({
      animation: { route: routeAnimation },
      ...others
    }) => (
      <FadeContainer routeAnimation={routeAnimation}>
        <Component {...others} />
      </FadeContainer>
    );

Trying to test css property of FadeContainer with specific props.

    import React from "react";
    import { configure, shallow, mount } from "enzyme";
    import Adapter from "enzyme-adapter-react-16";
    import toJson from "enzyme-to-json";
    import "jest-styled-components";
    import { withFadeAnimation } from "./lib/animationWrapper";
    
    configure({ adapter: new Adapter() });
    
    /// test css property with hoc function
    describe("withFadeAnimation hoc function test", () => {
      test("route props passing test", () => {
        const props = { animation: { route: "slideInUp" } };
        const testComponent = <div>123</div>;
        const hoc1 = withFadeAnimation(<testComponent />);
        const wrapper = mount(<hoc1 {...props} />);
        // expect(wrapper.find("div").at(0)).toHaveStyleRule("animation", "123");
        expect(toJson(wrapper)).toMatchSnapshot();
      });
    });

But I get the weird snapshot.

    exports[`withFadeAnimation hoc function test route props passing test 1`] = `
    <hoc1
      animation={
        Object {
          "route": "slideInUp",
        }
      }
    />
    `;

Why the FadeContainer is not rendered and How to test animation property of FadeContainer?

**Comment by MicheleBertoli** [comment]
Hey @yuanlai, your code is giving a warning:

> Warning: The tag `<hoc1>` is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.

And you should change your test to:

```js
test("route props passing test", () => {
  const props = { animation: { route: "slideInUp" } };
  const TestComponent = () => <div>123</div>;
  const Hoc1 = withFadeAnimation(TestComponent);
  const wrapper = mount(<Hoc1 {...props} />);
  expect(toJson(wrapper)).toMatchSnapshot();
});
```

Where:
- `TestComponent` is a component
- `TestComponent` is capitalised
- `TestComponent` is passed to `withFadeAnimation`
- `Hoc1` is capitalised

To make it work:

```js
exports[`withFadeAnimation hoc function test route props passing test 1`] = `
<Component
  animation={
    Object {
      "route": "slideInUp",
    }
  }
>
  <styled.div
    routeAnimation="slideInUp"
  >
    <div
      className=""
    >
      <TestComponent>
        <div>
          123
        </div>
      </TestComponent>
    </div>
  </styled.div>
</Component>
`;
```

I hope this helps.

**Comment by yuanlai** [comment]
Cool, very nice code.
