### ISSUE TITLE
Upcoming data attribute change in v4

### ISSUE THREAD

**Issue by probablyup** [styled-components/jest-styled-components#169]
Hey folks, just letting you know ahead of time that https://github.com/styled-components/jest-styled-components/blob/22d6192ff2c7cbf1e6dc5e2e139904b7ddf7978d/src/utils.js#L49 will need to be changed for styled-components v4.

`data-styled-components` -> `data-styled`

For more info, see https://github.com/styled-components/styled-components/pull/1919

Cheers

**Comment by probablyup** [comment]
/ping - now that the [beta is out](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112) it'd be awesome to get a patch cut to support the new attribute

I think it should probably be easy to support both at once

**Comment by fbring** [comment]
Hey @MicheleBertoli,
as you mentioned in #129 I think I prepared a working solution - but I can't commit because of a eslint error, which still seems to be a problem #112 .

I am sorry if it´s my fault, but it´s my first time trying to contribute to an open source project.

**Comment by MicheleBertoli** [comment]
You are awesome, @fbring, thanks for working on this.
I'm more than happy to support your first contribution.

Can you please silent eslint with `/* eslint-disable */` and submit a PR?
The secret internals seem to still be there so it shouldn't be related to #112.

I'm looking forward to seeing your code.
Cheers!
