### ISSUE TITLE
Error: No style rules found on passed Component

### ISSUE THREAD

**Issue by artooras** [styled-components/jest-styled-components#174]
Hi. I have a simple `styled-components` component that I'm trying to test with `jest-styled-components`.

**Button.js**

```
function UnstyledButton(props) {
  return (
    <button 
      className={props.className}>
      {props.children}
    </button>
  )
}

const Button = styled(UnstyledButton)`
  display: flex;
`

export default Button
```

But when I'm trying to test it with `toHaveStyleRule` (I use `react-testing-library`), I get the mentioned error.

**Button.test.js**

```
it('Button renders correctly', () => {
    const {container} = render(
      <Button />
    )
    const button = container.firstChild
    expect(button).toBeInTheDocument()
    console.log(prettyDOM(button))
    expect(button).toHaveStyleRule('display', 'flex')
})

```

The `console.log()` output is as follows:

```
<button
    class="sc-bdVaJa gJFSqb"
/>
```

Am I using `toHaveStyleRule` incorrectly?

**Comment by artooras** [comment]
I tried running the test with the latest version `6.1.1` and cannot reproduce the error anymore...

**Comment by artooras** [comment]
Having said that, I found another minor issue - the library can find a rule like `('cursor', 'pointer')`, but it fails to find a rule `('-webkit-text-stroke', '1px white'), although I have them side-by-side in code, in page source as well as in dev tools in Chrome.

**Comment by MicheleBertoli** [comment]
I'm glad to hear v6.1.1 fixed the issue, thanks @artooras.

I tried the code you described:

```js
const MyComponent = styled.div`
  -webkit-text-stroke: 1px white;
  cursor: pointer;
`

test('it works', () => {
  const tree = renderer.create(<MyComponent />).toJSON()

  expect(tree).toHaveStyleRule('-webkit-text-stroke', '1px white')
  expect(tree).toHaveStyleRule('cursor', 'pointer')
})
```

And it seems to work as expected.

Can you please open a separate issue with a non-working example so that I can look into it?
Thank you very much!
