### ISSUE TITLE
toHaveStyleRule doesn't find properties based on theme

### ISSUE THREAD

**Issue by artooras** [styled-components/jest-styled-components#177]
I know there was a [somewhat similar question](https://github.com/styled-components/jest-styled-components/issues/119), but that case is based on Enzyme's shallow rendering, while I'm using `react-testing-library`.

Here's the code:

```
import React from 'react'
import {render} from 'react-testing-library'
import 'jest-styled-components'
import theme from '../theme'

const MyComponent = styled.div`
  cursor: pointer;
  border-width: theme.line;
`

test('it works', () => {
  const {container} = render(<MyComponent />)
  const myComponent = container.firstChild
  expect(myComponent).toHaveStyleRule('cursor', 'pointer')
  expect(myComponent).toHaveStyleRule('border-width', theme.line)
})
```

The first `expect` statement passes. The second one fails with:

```
"Property 'border-width' not found in style rules"
    
    Expected
      "border-width: 1px"
    Received:
      "border-width: undefined"
```

It also fails if I write the test with an explicit value like so:

`expect(myComponent).toHaveStyleRule('border-width', '1px')
`

Any idea how I can make it work?

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue and providing a non-working example, @artooras.

Unless I'm missing something, that's not the way to use themes.
You should pass, for example, the theme as a prop, and then use the props in the template-string.

```js
const MyComponent = styled.div`
  border-width: ${props => props.theme.line};
`

test('it works', () => {
  const { container } = render(<MyComponent theme={theme} />)
  expect(container.firstChild).toHaveStyleRule('border-width', theme.line)
})
```

I hope this helps.

**Comment by artooras** [comment]
You're right, this was a simple mistake on my part. After all, I am rendering components without rendering the entire tree up to the App component which includes the ThemeProvider. Thanks!
