### ISSUE TITLE
Failed snapshot when use jest-puppeteer preset

### ISSUE THREAD

**Issue by dmitrymalakhov** [styled-components/jest-styled-components#178]
I use styled-components and jest-styled-components for tests. I need test with the use puppeteer and i added jest-puppeteer, but i got problem with snapshot in styled components.

![screenshot from 2018-09-03 15-47-30](https://user-images.githubusercontent.com/2477267/44987691-ba447480-af90-11e8-8e37-2a03c820390b.png)

**Comment by MicheleBertoli** [comment]
This is an interesting use-case, @dmitrymalakhov.
Do you mind providing a non-working example?
