### ISSUE TITLE
TypeScript definitions conflict with other global types

### ISSUE THREAD

**Issue by strax** [styled-components/jest-styled-components#179]
Version: 6.1.1

Since `index.d.ts` is not a module declaration file, interfaces defined inside the file _not_  in a namespace are visible in the global scope. For us, it causes a compilation error as another package exposes a global `interface Options` as well.

To fix, it should be possible to move the helper types into the scope of this module and only augment the `jest` namespace. If that sounds sensible, I can submit a pull request.

**Comment by MicheleBertoli** [comment]
Thanks for opening this issue, @strax.
Unfortunately, I'm not familiar with TypeScript and this typing gave us quite a few issues (e.g. #167).

It would be awesome if you could fix it once for all : )
I'm looking forward to reviewing your PR.

**Comment by tristanMatthias** [comment]
Hey @MicheleBertoli, I will submit a PR for this now :)

**Comment by motevallian** [comment]
I think the Options, Value and AsymmetricMatcher interfaces should have been moved into jest namespace to avoid being global.
It will be a simple fix.

**Comment by strax** [comment]
Thanks @tristanMatthias for taking this on! @MicheleBertoli could it be possible to make a new release of `jest-styled-components` which contains this fix?
