### ISSUE TITLE
Typescript support 

### ISSUE THREAD

**Issue by CosminIonascu** [styled-components/jest-styled-components#18]
Hi, can you offer support for typescript?  I am getting this error when I use  toMatchStyledComponentsSnapshot "[ts] Property 'toMatchStyledComponentsSnapshot' does not exist on type 'Matchers'."

**Comment by MicheleBertoli** [comment]
This is interesting, thanks @CosminIonascu.
Unfortunately I'm not a TypeScript expert, but I'll be more than happy to review a PR.

**Comment by davidka** [comment]
@CosminIonascu Does it work with you now? 
I can't import it in a typescript file

**Comment by CosminIonascu** [comment]
Yes, I created a global.d.ts file and added 
declare namespace jest {
    interface Matchers {
        toMatchStyledComponentsSnapshot(snapshotName?: string): void;
    }
}

**Comment by davidka** [comment]
How does your import looks like? Could You give me an example please?

**Comment by MicheleBertoli** [comment]
Hello @davidka @CosminIonascu, thanks for your comments.

Just to clarify:
- we do have a ts file: https://github.com/styled-components/jest-styled-components/blob/master/src/index.d.ts (please let me know if it works for you)
- we do NOT have the `toMatchStyledComponentsSnapshot` matcher anymore (see https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#400---2017-07-15)

**Comment by morajabi** [comment]
maybe ts-jest repo should help you?

**Comment by timhwang21** [comment]
If anyone is here after a Google adventure, if you are using Jest 24 with `ts-jest` and are using `importHelpers: true` in your `tsconfig.json`, pass a custom config to `ts-jest` with import helpers set to `false`. Apparently the helpers interfere with the setup of `jest-styled-components`.
