### ISSUE TITLE
Support for Styled Components v4?

### ISSUE THREAD

**Issue by alansouzati** [styled-components/jest-styled-components#183]
Any plans to support styled-components v4?

As per the peerDependency, it only supports v2 and v3: `styled-components@^2.0.0 || ^3.0.2`.

I decided to give it a try regardless, but it does not seem to work.

**Comment by alansouzati** [comment]
Actually I was using v4 beta1-2 which is a dev release and it is currently broken. If I revert to beta1 it works just fine.

**Comment by MicheleBertoli** [comment]
Hello @alansouzati, thanks for opening this issue.
I already started to investigate how to support v4, but there are [some issues](https://github.com/styled-components/styled-components/issues/1969#issuecomment-419633251) with Enzyme at the moment.
