### ISSUE TITLE
toHaveStyleRule errors if component is empty

### ISSUE THREAD

**Issue by guyfedwards** [styled-components/jest-styled-components#189]
When the component that has `.toHaveStyleRule` call on it, it errors. As you can see below, `expect(wrapper.find('Input__ValidationMessage').length).toBe(1)` passes.
![image](https://user-images.githubusercontent.com/1794071/45547544-060cde80-b819-11e8-819b-74ad4a0b00de.png)

Adding some child text to the component causes the test to pass.
![image](https://user-images.githubusercontent.com/1794071/45547560-1329cd80-b819-11e8-8de5-93158f1e3887.png)

**Comment by MicheleBertoli** [comment]
Thank you very much for opening this issue, @guyfedwards.
Do you mind sharing your component and test so that I can repro?

**Comment by guyfedwards** [comment]
Sure @MicheleBertoli, you can find the component [here](https://github.com/weaveworks/ui-components/blob/react-16.5-enzyme/src/components/Input/Input.js) and the test [here](https://github.com/weaveworks/ui-components/blob/react-16.5-enzyme/src/components/Input/Input.test.js). You can see the second to last test is the culprit, with a comment referencing this issue.

**Comment by MicheleBertoli** [comment]
Hello @guyfedwards, I saw that https://github.com/weaveworks/ui-components/pull/379 was merged.
Can we close this, or does the issue still persist?

**Comment by guyfedwards** [comment]
Oh sorry, I probably deleted the branch :man_facepalming: The issue still persists and you can see on master [component](https://github.com/weaveworks/ui-components/blob/master/src/components/Input/Input.js) & [test](https://github.com/weaveworks/ui-components/blob/master/src/components/Input/Input.test.js#L66)

**Comment by MicheleBertoli** [comment]
Thanks for providing more information, @guyfedwards.
Unless I'm missing something, the test is passing on master, right?
(I cloned the repo and it seems to work as expected)

In any case, my recommendation is to set the `displayName`, like:
```js
ValidationMessage.displayName = 'ValidationMessage'
```

And then:
```js
expect(wrapper.find('ValidationMessage')).toHaveStyleRule(
  'visibility',
  'visible'
);
```

**Comment by guyfedwards** [comment]
@MicheleBertoli The test passes as I have added the lines 
```
      // https://github.com/styled-components/jest-styled-components/issues/189
      message: 'Derp!',
```
To make it pass, that comment referencing this issue as the reason for the content being set.
If you remove the `message`, thus setting the content to be empty, then the test fails.

Apologies for not being clearer

**Comment by MicheleBertoli** [comment]
Yay! Found the issue, and fixed it.
Please install `v6.2.1`.
Thank you very much, @guyfedwards.
