### ISSUE TITLE
Unexpected token ... after upgrading to 6.2.1

### ISSUE THREAD

**Issue by albert-olive** [styled-components/jest-styled-components#192]
Hi,

After upgrading to ```6.2.1``` all my tests breaks:

```
.../node_modules/jest-styled-components/src/toHaveStyleRule.js:104
    const normalizeOptions = ({ modifier, ...options }) =>
                                          ^^^
    SyntaxError: Unexpected token ...
t ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (node_modules/jest-styled-components/src/index.js:1:114)
      at Object.<anonymous> (src/setupTests.js:11:51)
```

And my setupTests.js:

```
import 'jest-enzyme';
import 'jest-styled-components';

import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

My package versions are:

```
"styled-components": "3.2.3",
"jest-enzyme": "6.1.2",
"react": "16.5.2",
```

Anyone has the same problem? 

Thanks

**Comment by mofax** [comment]
just introduced `jest-styled-components` into a project, and got hit with this...

**Comment by aserrabl** [comment]
I'm facing the same issue when adding it to a project. From which version are you updating @albert-olive? Tried also 6.0.0 with no luck. 5.0.1 works great.

My versions are
`    
"react": "16.5.0",
"jest": "21.2.1",
 "styled-components": "3.4.9"
`

**Comment by albert-olive** [comment]
Hi @aserrabl, in my previous comment, you have my versions. Didn't updated yet because I'm having already this problem

**Comment by MicheleBertoli** [comment]
Thanks for opening this issue, @albert-olive, and thanks for your comments, @mofax @aserrabl @SarantopoulosKon.

I assume you are using a version of node < 8.6, right?
Source: https://node.green/#ES2018-features-object-rest-spread-properties

**Comment by mofax** [comment]
The issue disappeared after I moved up to node v9.9.0

**Comment by albert-olive** [comment]
Me too @MicheleBertoli

**Comment by devrelm** [comment]
The package.json can/should define the `engine` field to show a warning if a supported version of node is not installed.

https://docs.npmjs.com/files/package.json#engines

Alternatively (and preferably), `toHaveStyleRule.js` should be updated to not use a rest spread prop. Node 6 [is still supported until April 2019](https://github.com/nodejs/Release), so it's probably best if we continue support for that as well.

**Comment by jdrub** [comment]
I ran into this too, for a quick temporary fix you can just tell jest to transform this package by adding the following line to your jest config:
`"transformIgnorePatterns": ["/node_modules\/(?!(jest-styled-components)\/).*/"]`
