### ISSUE TITLE
Mismatch between styled-component generated value and base value

### ISSUE THREAD

**Issue by RomainGoncalves** [styled-components/jest-styled-components#194]
Hello.

I'm building a component that needs to be themed by the application using it.
At the moment it looks like this:

```javascript
export const StyledButton = styled.button`
  background-color: ${props => props.theme.colors.primary};
`;

const Button = () => {
  return (
    <StyledButton>
      {children}
    </StyledButton>
  );
};
```

The test is simple too:

```javascript
mounted = mountWithTheme(
    <Button onClick={() => {}} btnType="secondary">Text</Button>,
    templateStyles,
);

expect(mounted).toHaveStyleRule('color', templateStyles.colors.primary);
```
And finally my styles, a simple object:

```javascript
export default {
    colors: {
      primary: 'rgb(86, 155, 195)',
  },
};
```

When testing my component I get a mismatch error. The error is simple, in the rendered component, it's missing spaces after the commas in rgb values. Like so:
<img width="496" alt="screen shot 2018-10-10 at 10 55 25" src="https://user-images.githubusercontent.com/1366477/46724773-0747f480-cc7b-11e8-8b24-770900943b18.png">

It would be easy enough to fix by simply removing the spaces in my base values but I don't really want to do that. Did anyone ever experience this?

**Comment by MicheleBertoli** [comment]
Thanks for opening this issue, @RomainGoncalves.
We are discussing this in #98.
