### ISSUE TITLE
Create-React-App v0.9.5 component snapShot tests not working

### ISSUE THREAD

**Issue by oguzzkilic** [styled-components/jest-styled-components#20]
Node -v : v6.9.5
Styled-Components : v1.4.4
Create-React-App: v.0.9.5

I can not run jest-styled-components tests.

![screen shot 2017-05-25 at 13 55 04](https://cloud.githubusercontent.com/assets/3652404/26447586/ccf8ecd6-4151-11e7-98e6-4118d2c84e08.png)

**Comment by luftywiranda13** [comment]
#7

**Comment by MicheleBertoli** [comment]
Thanks @oguzzkilic @luftywiranda13 
I can confirm that this package works with Jest 19+.
The latest version of CRA ships with Jest v20.
