### ISSUE TITLE
Enzyme snapshot vs React renderer snapshot

### ISSUE THREAD

**Issue by rlesniak** [styled-components/jest-styled-components#200]
I cant understand why I am getting strange `styled` wrappers arund my html elements.
Take a look on my snapshot:
```js
exports[`HistoryRow mount 1`] = `
.c0 {
  font-size: 16px;
}

.c1 {
  color: red;
}

<styled.div>
  <div
    className="c0"
  >
    <styled.button>
      <button
        className="c1"
      />
    </styled.button>
  </div>
</styled.div>
`;

exports[`HistoryRow test renderer 1`] = `
.c0 {
  font-size: 16px;
}

.c1 {
  color: red;
}

<div
  className="c0"
>
  <button
    className="c1"
  />
</div>
`;
```

When I do Enzyme's `mount` then I am getting unneccesary wrapers like `<styled.div>` or `<styled.button`, I want to look my snapshot exactly as made with ` testRenderer.create`.
For small components its ok, but for more complex there is around 50% more lines than with testRenderer, and gets repeated props, for instance:
```
<Styled(Component)
        enlarge={true}
        height={24}
        src="<svg><path /></svg>"
        width={24}
      >
        <Component
            className="c1"
            enlarge={true}
            height={24}
            src="<svg><path /></svg>"
            width={24}
        >
```

What I am doing wrong?

I am using:
```
"enzyme": "3.7.0",
"enzyme-adapter-react-16": "1.6.0",
"enzyme-to-json": "3.3.4",
"jest": "23.6.0",
"jest-styled-components": "6.2.0",
```

**Comment by MicheleBertoli** [comment]
Hello @rlesniak, thanks for opening this issue.

You aren't doing anything wrong, this is the way it works.
Please give it a go to [this repo's tests](https://github.com/styled-components/jest-styled-components/blob/master/test/__snapshots__/styleSheetSerializer.spec.js.snap) too.

I recommend using the test renderer to minimise the noise.
