### ISSUE TITLE
getChildContext not working in current version of styled-component

### ISSUE THREAD

**Issue by jitenderchand1** [styled-components/jest-styled-components#209]
Following example is not working with version `^4`. It continued to throw error and say `instance.getChildContext` is not a function 

```
import React from 'react';
import { shallow, mount } from 'enzyme';
import { ThemeProvider } from 'styled-components';

import theme from './theme';


export const shallowWithTheme = (children, options) => {
  const wrapper = shallow(<ThemeProvider theme={theme}>{children}</ThemeProvider>, options);
  const instance = wrapper.root().instance();
  return wrapper.shallow({ context: instance.getChildContext() }).dive();
};


export default { shallowWithTheme };

```

**Comment by serhiiminin** [comment]
Yes, I have the same issue. I've tried to use `styled-components: ^3.4.10` and it worked for me

**Comment by mxstbr** [comment]
This is an issue with enzyme not supporting React v16 well, including the newest context API and `React.forwardRef` I think.

**Comment by serhiiminin** [comment]
Where is it better to keep `shallowWithTheme, mountWithTheme`? If I place it to my `enhancers`  then `eslint` asks me to install `enzyme` as a dependency and not as a` devDependency`

**Comment by jitenderchand1** [comment]
Fine, So I ended up doing the following which works fine but only cons is here that I have import the child component again in order to further action with component. Will there any solution for this?



```
it('should enable the search button while the input is not empty', () => {
    const wrapper = shallowWithTheme(<OrderSearch history={historyMock} />);
    wrapper.setState({ searchTerm: '111' });
    expect(wrapper.find(SearchButton).dive().props().isDisabled).toBe(false);
  });
```
