### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by Madebymaurice** [styled-components/jest-styled-components#219]
Hi @MicheleBertoli  and thanks for your job.

I'm using the next version of jest-styled-components for styled-components v4 and I've got a warning because it use `styled-components@^2.0.0 || ^3.0.2`. I know it's a work-in-progress version but would you mind if I update peer dependency ?

Thanks !

**Comment by cellog** [comment]
This results in an npm warning every time any install is done. Considering it is just noise, it causes issues for us, a release with this fix would be much appreciated. Would you like a PR?

**Comment by cellog** [comment]
It looks like #184 addresses this

**Comment by Madebymaurice** [comment]
Great ! Thanks for your help !
