### ISSUE TITLE
jest-styled-components@6.3.1" has incorrect peer dependency "styled-components@^2.0.0 || ^3.0.2".

### ISSUE THREAD

**Issue by basslagter** [styled-components/jest-styled-components#220]
When installing (using Yarn) the following warning is shown:

jest-styled-components@6.3.1" has incorrect peer dependency "styled-components@^2.0.0 || ^3.0.2".

**Comment by castiarena** [comment]
Same here, also using yarn

**Comment by iDuuck** [comment]
Somehow a duplicate.

You might want to chime in here: https://github.com/styled-components/jest-styled-components/issues/191

**Comment by probablyup** [comment]
This is fixed in 6.3.3
