### ISSUE TITLE
Snapshots revert to UNDEFINED

### ISSUE THREAD

**Issue by Madebymaurice** [styled-components/jest-styled-components#222]
Hi Everyone,

Part of my package.json
`"dependencies": {
"styled-components": "4.1.3",
},
"devDependencies": {
"babel-jest": "21.2.0",
"jest": "21.2.1",
"jest-cli": "21.2.1",
"jest-styled-components": "^7.0.0-2",
"react": "16.6.3",
"react-dom": "16.6.3",
},
`

After updating styled-components to `4.1.3`, some of my snapshots update from `<styled.div>` to `<UNDEFINED>` after debugging, I found that the snapshots updated all have a typeof = `react.forward_ref` and the jest test only if the type is a string or a function so as the forwardRef is now a object i've got a UNDEFINED.

I've tried to upgrade my jest to `23.6.0` version but snapshots then update from `<UNDEFINED>` to `<ForwardRef>`

Any idea of a way to fix this ?
Thanks for your help.

**Comment by Madebymaurice** [comment]
Hi, after debugging again, we found that the snapshot reverted to `<UNDEFINED>` use to all have a intermediate render which cause the `<ForwardRed>` so refacto the code for prevent the intermediate rendering solve the issue.

Hope it helps !

**Comment by Michal-Przybylski** [comment]
can you provide more details about the fix? I have the same problem, if I switch to syles-components 3.4 its working but on ^4 its not

**Comment by Madebymaurice** [comment]
I my case, in the code we use to render the component one first time and in the test we render a second time with a jest function. So I refacto the code and remove the second re-render (in the test) and the snapshot passed normally without Undefined.
