### ISSUE TITLE
Migrate to Styled Components v4 breaks snapshots

### ISSUE THREAD

**Issue by daraclare** [styled-components/jest-styled-components#223]
Hi, thanks for a great library :) 

I've updated to Styled Components v4, and while everything seems to be fine, the snapshots have broken, but only the styling. Could this be a jest-styled-components issue? I don't want to update any snapshots until I really understand what the changes are.

I've included an image below — a lot of the changes seem to be to class names i.e. from `c1` to `c0`, but there is also removed styles which appear further down, see attached. Anyone know why this is happening? Any advice would be much appreciated!

<img width="430" alt="screen shot 2019-01-11 at 16 02 12" src="https://user-images.githubusercontent.com/5235711/51045090-a8b44e80-15ba-11e9-9c45-ff5ed82ea288.png">

**Comment by daraclare** [comment]
Is this related to #191 ?

**Comment by probablyup** [comment]
Sometimes major versions of styled-components include changes to how and when we generate dynamic styles. As long the styles are all present in the revised snapshots (perhaps grouped differently), I wouldn't worry about it.
