### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by SirPhemmiey** [styled-components/jest-styled-components#226]
Hi, i'm trying to test my React Native component which has styled-components used. When i run the test with jest, i'm getting `
Cannot find module 'react-dom' from 'styled-components.cjs.js'
`
I also used the module `jest-styled-components`. Still shows the same. 

Please help

**Comment by mdapper** [comment]
Did you used the native import on your test?

```js
import 'jest-styled-components/native'
```

**Comment by neutrous** [comment]
@SirPhemmiey Make sure not to import components by `import { withTheme }  from 'styled-components'`. React Native relevant imports should come from `'styled-components/native'`.

[Here is another solution](https://github.com/styled-components/styled-components/issues/1451#issuecomment-361661563)

**Comment by JimmySorza** [comment]
> @SirPhemmiey Make sure not to import components by `import { withTheme } from 'styled-components'`. React Native relevant imports should come from `'styled-components/native'`.
> 
> [Here is another solution](https://github.com/styled-components/styled-components/issues/1451#issuecomment-361661563)

thanks @SirPhemmiey the import solution works for me
