### ISSUE TITLE
not rendering CSS in styled-components v5 / jest-styled-components beta

### ISSUE THREAD

**Issue by tinynumbers** [styled-components/jest-styled-components#285]
We are attempting to upgrade from styled-components v4 and jest-styled-components 6.3.3, and have installed the following versions

* @testing-library/jest-dom 4.2.4
* @testing-library/react 9.3.2
* @testing-library/react-hooks 3.2.1
* jest-styled-components 7.0.0-beta.2
* react 16.8.6
* react-dom 16.8.6
* react-is 16.8.6
* react-test-renderer 16.12.0
* styled-components 5.0.0-rc.2

Prior to the upgrade everything was working fine with snapshot testing as well as the `.toHaveStyleRule` matcher (using `@testing-library/react`'s `render`).

After the upgrade, it appears as if we don't even have `jest-styled-components` installed. And I've tried importing it both globally (using the `setupFilesAfterEnv` approach described in the README) and directly within each test file. But the snapshots have the hashed classnames now and do not include the CSS, and the `toHaveStyleRule` matcher reports `"No style rules found on passed Component"`.

Any suggestions of additional setup that may need tweaking, or is anyone else also seeing this issue?

Snapshot example:

```jsx
import React from 'react';
import { render } from '@testing-library/react';

import Link from '.';

describe('Link', () => {
  it('renders correctly', () => {
    const { container } = render(<Link to="/" text="text" />);

    expect(container).toMatchSnapshot();
  });
  ...etc...
```

Style matcher example:

```jsx
  it('renders the vertical variant correctly', () => {
    const { container } = render(
      <CheckboxGroup items={[{ label: 'Item 1' }]} vertical />,
    );

    const itemsContainer = container.firstChild.firstChild;

    expect(itemsContainer).toHaveStyleRule('flex-direction', 'column');
  });
```

**Comment by tinynumbers** [comment]
By the way, I've confirmed that the same failure is happening when using styled-components 5.0.0-rc.1 as well.

**Comment by tinynumbers** [comment]
I believe my issue here was with mis-matched versions of some of the React modules. Whatever the case, it does not appear to be an issue with `jest-styled-components`.

**Comment by joshjg** [comment]
@tinynumbers Could you provide more details about how you solved this? I am experiencing the same issue.
