### ISSUE TITLE
No style rules when testing directly a styled components from babel macro

### ISSUE THREAD

**Issue by dorianamouroux** [styled-components/jest-styled-components#325]
I'm currently updated `styled-components` of my project to the latest version (`"jest-styled-components": "^7.0.2"` & `"styled-components": "^5.1.1"`).

Although the great majority of my tests pass, some of them have the following error message: `No style rules found on passed Component`.

After investigation, I noticed the only failing tests were the one where the styled components is exported directly, which are styled-components created with the babel macro. I tried to create those components without the babel macro and the tests are passing. 

I created a repository to reproduce the bug:

https://github.com/dorianamouroux/styled-components-test-issue

The component:

```js
import styled from 'styled-components'
import styledMacro from 'styled-components/macro'

export const Tag = styled.div`
  background-color: orange;
`

export const TagMacro = styledMacro.div`
  background-color: orange;
`
```

The spec:

```js
import React from 'react'
import { shallow } from 'enzyme'

import { Tag, TagMacro } from './Tag'

describe('Tag', () => {
  it('no macro - has the right color', () => {
    // test passes, no babel macro
    expect(shallow(<Tag />)).toHaveStyleRule('background-color', 'orange')
  })

  it('macro - has the right color', () => {
    // fail, with the babel macro
    expect(shallow(<TagMacro />)).toHaveStyleRule('background-color', 'orange')
  })

  it('macro - has the right color', () => {
    // test passes, with a work around
    function WrapperTag() {
      return <TagMacro />
    }
    expect(shallow(<WrapperTag />).find(TagMacro)).toHaveStyleRule('background-color', 'orange')
  })
})
```

I'm using Enzyme, React and Styled-components macro. All with the latest version.

**Comment by VarunBalakrishna** [comment]
+1 same issue for me

**Comment by VarunBalakrishna** [comment]
I figure out a workaround adapted from https://github.com/styled-components/jest-styled-components/issues/290#issuecomment-575498923

If you're using the babel macro (import styled from "styled-components/macro";), you can create a .babel-plugin-macrosrc.js (https://styled-components.com/docs/tooling#experimental-config) in your project root with contents:

module.exports = {
    styledComponents: {
        ...(process.env.TEST === "true" ? { ssr: false, displayName: false } : {}),
    },
};
and run your test script with TEST=true in front of it. eg. TEST=true react-scripts test.

**Comment by Tokimon** [comment]
And i have posted the actual reason for this here (it is due to too aggressive class name filtering really):
https://github.com/styled-components/jest-styled-components/issues/297#issuecomment-639362675
