### ISSUE TITLE
Inconsistent toHaveStyleRule testing results

### ISSUE THREAD

**Issue by mattcarlotta** [styled-components/jest-styled-components#335]
I have a simple styled component that interpolates some CSS properties based upon passed in props:
```js
import styled from "styled-components";

const Flex = styled.div`
  flex-direction: ${({ direction }) => direction || "row"};
  display: flex;
  align-items: center;
  height: 100%;
  width: 100%;
  flex-wrap: ${({ wrap }) => (wrap ? "wrap" : "nowrap")};
  justify-content: ${({ justify }) => justify || "start"};
`;

export default Flex;
```
And the accompanying test (jest + enzyme):
```js
import Flex from "../index";

describe("Flex", () => {
  let wrapper;
  beforeEach(() => {
    wrapper = mount(<Flex data-testid="flex" />);
  });

  it("renders without errors", () => {
    expect(wrapper).toExist();
    expect(wrapper).toHaveStyleRule("flex-direction", "row");
    expect(wrapper).toHaveStyleRule("flex-wrap", "nowrap");
    expect(wrapper).toHaveStyleRule("justify-content", "start");
  });

  it("sets 'flex-direction' to a 'column' when passed a 'direction' prop", () => {
    wrapper.setProps({ direction: "column" });
    expect(wrapper).toHaveStyleRule("flex-direction", "column");
  });

  it("sets 'flex-wrap' as a 'wrap' when passed a 'wrap' prop", () => {
    wrapper.setProps({ wrap: "true" });
    expect(wrapper).toHaveStyleRule("flex-wrap", "wrap");
  });

  it("sets 'justify-content' as a 'center' when passed a 'justify' prop", () => {
    wrapper.setProps({ justify: "center" });
    expect(wrapper).toHaveStyleRule("justify-content", "center");
  });
});
```

In this [project](https://github.com/mattcarlotta/nextjs-ssr-kit), the test passes:
![](https://i.imgur.com/Yq1GWhf.png)

In this [project](https://github.com/mattcarlotta/my-website-ssr), which is bootstrapped from the above, the same exact test fails:
![](https://i.imgur.com/k6F8vJx.png)

**Comment by enjoijkee** [comment]
I just experienced almost the same thing.
Two same styled components in two different files, one file passed tests, another did not with `No style rules found on passed Component`. I found some [related issues](https://github.com/styled-components/jest-styled-components/issues/294) and everyone is talking about babel-plugin-styled-components, but I don't have it in my project so I don't have a clue what's going on here.

**Comment by mattcarlotta** [comment]
The problem is related to this [issue](https://github.com/styled-components/jest-styled-components/issues/338) which (unknown to me) was also mentioned [here](https://github.com/styled-components/jest-styled-components/issues/297#issuecomment-639362675); on the same note, that recommended solution **doesn't** work. The workaround for me was to inline `toHaveStyleRule` within my project's test setup and by also removing the [staticClassNames](https://github.com/styled-components/jest-styled-components/blob/5448282e46b1a373a3b87f6ad10ea1541cdefec5/src/toHaveStyleRule.js#L82) piece of code. Doing so, resulted in 100% expected test results. The solution can be found [here](https://github.com/mattcarlotta/nextjs-ssr-kit/blob/master/src/utils/toHaveStyleRule/rules.ts#L23-L28). Until this gets fixed (or if it gets fixed -- this repo seems unmaintained), I'd recommend sticking to styled-components v4 & jest-styled-components v6 OR inlining the rule for styled-components v5 within your project.

**Comment by pkhodaveissi** [comment]
This is still happening with styled-componentV5 and jest-styled-componentV7

but it's alright with  styled-componentV4 and jest-styled-componentV6

Are there any breaking changes in the latest versions?

**Comment by pkhodaveissi** [comment]
This is still happening with styled-componentV5 and jest-styled-componentV7

but it's alright with  styled-componentV4 and jest-styled-componentV6

Are there any breaking changes in the latest versions?
