### ISSUE TITLE
toHaveStyleRule does not work correctly with negation

### ISSUE THREAD

**Issue by noahnu** [styled-components/jest-styled-components#344]
Related: https://github.com/styled-components/jest-styled-components/pull/206/files

Steps to reproduce:

```jsx
const Button = styled.button`
    background-color: blue;
`

// this should pass, b/c font-size does not exist
expect(Button).not.toHaveStyleRule('font-size') 

// this should fail, b/c background-color exists
expect(Button).not.toHaveStyleRule('background-color') 
```

The latter assertion actually passes, because `background-color: undefined` does not exist.

---

Note that there is a workaround. You can supply a matcher as the expected value:

```
expect(wrapper).not.toHaveStyleRule('background-color', expect.any(String))
```

Main concern here is consistency. I'd actually be in favour of going a step further and saying that an `undefined` second parameter should be treated equivalent to `expect.any`, although that'd definitely be a breaking change (which shouldn't deter a fix).

**Comment by noahnu** [comment]
I put up a PR to fix this #345

**Comment by noahnu** [comment]
Related https://github.com/styled-components/jest-styled-components/issues/303

**Comment by noahnu** [comment]
Bump

**Comment by stonebk** [comment]
Hey maintainers, 👋🏻 , is it possible to get some 👀  on this bug and pull request? 🙏🏻 

The suggested syntax of `expect(tree).not.toHaveStyleRule('opacity')` does not work and allows bugs in your code to slip through the cracks. I've gone and rewritten all my tests to use the `expect(tree).not.toHaveStyleRule('opacity', expect.any(String))` syntax, which works, but does not feel natural to write at all, and is easy to forget.

It would be great if we could get #345 merged.

Thanks!

**Comment by noahnu** [comment]
@probablyup Is there any way to help get this merged?
