### ISSUE TITLE
Error while jest test after adding jest-styled-components: TypeError: global.beforeEach is not a function

### ISSUE THREAD

**Issue by Git-Hub-User-0** [styled-components/jest-styled-components#368]
Hi,
I am getting error 
> | TypeError: global.beforeEach is not a function
> | in below file
  > | import "jest-styled-components";

while running jest test.
I have added jest-styled-component in jest setup file.

Here are the configs:
_"react": "^16.9.0",
"react-dom": "~16.9.0",
"react-native": "^0.64.0",
"jest": "^26.6.3",
"jest-styled-components": "^7.0.4",
"react-test-renderer": "^17.0.2",
"styled-components": "^5.2.3"_

And if i am not adding jest-styled-component, then i am getting error like this:
>| The above error occurred in the <Context.Consumer> component** in **/node_modules/styled-components/native/dist/styled-components.native.cjs.js:5944:29**

Can you please help.
Thanks in advance.

**Comment by Git-Hub-User-0** [comment]
oh well i removed jest-styled-components for now, and added <ThemeProvider> to the component in my something.test.ts file while rendering, and this context issue was fixed.
I guess jest-styled-component should be working now as well.
So closing this.

**Comment by AilsonFreire** [comment]
I'm facing the same problem, could show how did you fixed @Git-Hub-User-0  please?
