### ISSUE TITLE
RFH: How to use this test library with themes

### ISSUE THREAD

**Issue by jonedge** [styled-components/jest-styled-components#38]
Hi there

I'm looking to use this to test my styled components, but cannot seem to figure out the best solution to provide my theme using theme provider. 

can you advise ?

**Comment by MicheleBertoli** [comment]
Hello @jonedge, thanks for your question.

To test components wrapped into a `ThemeProdiver` I would use the `react-test-renderer` with the `toMatchStyledComponentsSnapshot` matcher.

For example, given this component:

```js
const Button = styled.button`
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border-radius: 3px;

  /* Color the border and text with theme.main */
  color: ${props => props.theme.main};
  border: 2px solid ${props => props.theme.main};
`

Button.defaultProps = {
  theme: {
    main: 'palevioletred',
  },
}

const theme = {
  main: 'mediumseagreen',
}
```

And the following test:
```js
test('ThemeProvider', () => {
  const tree = renderer.create(
    <div>
      <Button>Normal</Button>
      <ThemeProvider theme={theme}>
        <Button>Themed</Button>
      </ThemeProvider>
    </div>,
  ).toJSON()

  expect(tree).toMatchStyledComponentsSnapshot()
})
```

This is going to be snapshots:
```js
exports[`ThemeProvider 1`] = `
.fkldfe {
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border-radius: 3px;
  color: palevioletred;
  border: 2px solid palevioletred;
}

.fMpVkM {
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border-radius: 3px;
  color: mediumseagreen;
  border: 2px solid mediumseagreen;
}

<div>
  <button
    className="sc-bdVaJa fkldfe"
  >
    Normal
  </button>
  <button
    className="sc-bdVaJa fMpVkM"
  >
    Themed
  </button>
</div>
`;
```

**Comment by jonedge** [comment]
Thanks @MicheleBertoli, that was a huge help.

For anyone who comes across this in future, I've also been using the following to check that specific styling is being applied:

```
const component = renderer.create(<ThemeProvider theme={theme}><Button /></ThemeProvider>)
expect(component).toHaveStyleRule('color', '#000000')
```

**Comment by codeangler** [comment]
would it be different for use of styled-components ```withTheme```?

`import React from 'react';
import PropTypes from 'prop-types';
import { Col, Row } from 'react-styled-flexboxgrid';
import styled, { withTheme } from 'styled-components';
import User from 'react-icons/lib/fa/user';
import Hamburger from 'react-icons/lib/fa/bars';
import logo from '../../../shared/assets/images/logo.svg';

const someInformation = 'Sign Out';
const tagLine = 'Amazing'.toUpperCase();

// Styled Components
const HeaderStyled = styled.div`
  background: ${props => props.theme.gravel};
  padding: 0 1.5em;
`;

const Header = ({ theme = 'water' }) => (
  <HeaderStyled>
    <Row middle="xs">
      <Col xs={9} md={9}>
        <Row middle="xs" start="xs">
          <Col>
            <img src={logo} alt="Brand Logo" className="" />
          </Col>
          <Col xs>
            { tagLine }
          </Col>
        </Row>
      </Col>
      <Col xs>
        <Row end="xs" >
          <Col md xs={false}>
            <User /> | {someInformation}
          </Col>
          <Col xs md={false}>
            <Hamburger size={24} color={theme.water} />
          </Col>
        </Row>
      </Col>
    </Row>
  </HeaderStyled>
);

Header.defaultProps = {
  theme: 'water'
};

Header.propTypes = {
  theme: PropTypes.shape({
    water: PropTypes.string
  })
};


export default withTheme(Header);`  **note:  `withTheme(Header)`**

`
import React from 'react';
import styled, { withTheme, ThemeProvider } from 'styled-components';
import { serializer, matcher } from 'jest-styled-components';
import renderer from 'react-test-renderer';
import colors from '../../../shared/styledTheme';
import toJSON from 'enzyme-to-json';
import Header from './Header';


it('react-test-renderer', () => {
  const tree = renderer.create(
    <ThemeProvider theme={colors}>
      <Header />
    </ThemeProvider>
    ).toJSON();

  expect(tree).toMatchStyledComponentsSnapshot()
})
`

**Comment by codeangler** [comment]
so I changed the last line in my test to:

```
  expect(withTheme(tree)).toMatchStyledComponentsSnapshot()
```

**Comment by MicheleBertoli** [comment]
Hello @codeangler, you are already exporting your `Header` wrapped into `withTheme` so you shouldn't need to wrap it again. 
Can you please provide more information about what's the current behaviour and what you would expect? 
Thanks!
