### ISSUE TITLE
V7's toHaveStyleRule don't work with styled-componentsV5

### ISSUE THREAD

**Issue by pkhodaveissi** [styled-components/jest-styled-components#389]
For context:
https://github.com/styled-components/jest-styled-components/issues/294

what does this line do? 
[`const isStyledClass = (className) => /^(\w+(-|_))?sc-/.test(className);`](https://github.com/styled-components/jest-styled-components/blob/e1be59f1b2f6879b34936c0adbeec63396db9697/src/toHaveStyleRule.js#L7)
and why it's necessary to have it in. this function
[`hasClassNames`](https://github.com/styled-components/jest-styled-components/blob/e1be59f1b2f6879b34936c0adbeec63396db9697/src/toHaveStyleRule.js#L73)

I like to submit a PR to fix this so It'll be a great help if you could explain this to me.

**Comment by bchiong** [comment]
I was wondering the same thing too. In my case, our components have a different namespace which gets overlooked by `toHaveStyleRule`

**Comment by cdbenj** [comment]
I was wondering the same thing too. In my case, our components have a different namespace which gets overlooked by `toHaveStyleRule`
