### ISSUE TITLE
No feedback on what has changed for nested components

### ISSUE THREAD

**Issue by soosap** [styled-components/jest-styled-components#4]
Tried and it works great. Just for nested components I do not get any feedback on what changed.

That's the component: I want to build a `<ButtonGroup />`.
![image](https://cloud.githubusercontent.com/assets/7187705/24995461/2f089500-202f-11e7-98fb-c5ea8b30eebf.png)

However, the only feedback I get through snapshot testing is that something inside the styled-component has changed - no feedback whatsoever on what has changed. Is there a way to have feedback also on nested components?

![image](https://cloud.githubusercontent.com/assets/7187705/24995536/7023c64a-202f-11e7-9a87-8e9d38e1605c.png)

**Comment by MicheleBertoli** [comment]
Thank you very much @soosap, I fixed the issue in [1.3.3](https://github.com/styled-components/jest-styled-components/releases/tag/v1.3.3).

Here is an example:

<img width="220" alt="screen shot 2017-04-16 at 10 23 27 pm" src="https://cloud.githubusercontent.com/assets/1308971/25074488/a0defac2-22f3-11e7-9ae8-d8fa439474c5.png">
