### ISSUE TITLE
Doesn't seem to support Jest 28.x.x

### ISSUE THREAD

**Issue by Lkleven** [styled-components/jest-styled-components#414]
Hi, I have tried upgrading Jest from 27 to 28 and it seems that jest-styled-components doesn't do anything after the upgrade. 

I have code similar to your examples 
```
import React from 'react';
import { render } from '@testing-library/react';
import 'jest-styled-components';
import styled from 'styled-components';

const Button = styled.button`
  color: yellow;
`;

describe('Test', () => {
  it('works', () => {
    const { container } = render(<Button />);
    expect(container.firstChild).toMatchSnapshot();
  });
});
```

But the snapshot still have the dynamic classname from styled-components and doesn't include the actual styles:
```
exports[`Test works 1`] = `
<button
  class="sc-bczRLJ bqIyce"
/>
```

Any input on this would be greatly appreciated.

**Comment by kungfutse** [comment]
Same thing with Jest 29

**Comment by dylang** [comment]
I was able to work around this by changing the test running from `testRunner: "jest-jasmine2"` to the default. I don't know why this fixes it.

**Comment by Lkleven** [comment]
> I was able to work around this by changing the test running from `testRunner: "jest-jasmine2"` to the default. I don't know why this fixes it.

I already used the default testRunner `jest-circus/runner` so i figured i might as well try and change to `jest-jasmine2`, and it actually works. Not really sure why though.

Closing the issue for now as it seems to be testRunner related

**Comment by buugaaga** [comment]
This issue is not resolved. Need to update jest version in dependencies.

**Comment by daraclare** [comment]
I'm having this issue with Jest 28 and 29,changing the runner doesn't help. Can this be reopened?

**Comment by mmakarin** [comment]
Same here
