### ISSUE TITLE
TypeError: global.beforeEach is not a function

### ISSUE THREAD

**Issue by supminn** [styled-components/jest-styled-components#431]
I am new to `jest-styled-components`. I have created a react component and added styles using `styled-components`
However, while adding the following test, I am getting these errors:

## Component
```js
const StyledImage = styled.img`
  height: auto;
  margin: 0.5rem;
  border-radius: 0.5rem;
  width: ${(props) => {
    switch (props.size) {
      case "small":
        return "6rem";
      case "medium":
        return "12rem";
      case "large":
        return "14rem";
      default:
        return "12rem";
    }
  }};
`;
function Image({ src, title, size }) {
  return <StyledImage src={src} alt={title} size={size} />;
}
```

## Test file
```js
import { render, screen } from "@testing-library/react";
import { Image } from "./Image";
import { describe, expect, test } from "vitest";
import matchers from "@testing-library/jest-dom/matchers";
expect.extend(matchers);
import "jest-styled-components";

describe("Image", () => {
  test("renders an image with the correct size", () => {
    render(<Image src="test.jpg" title="Test image" size="small" />);
    const imageElement = screen.getByAltText(/test image/i);
    expect(imageElement).toBeInTheDocument();
    expect(imageElement).toHaveStyleRule("width: 6rem");
  });
});
```
## Package version
```js
"styled-components": "^6.0.6"
"jest-styled-components": "^7.1.1",
```

### Error Message screenshot
<img width="683" alt="Screenshot 2023-08-03 at 9 12 48 PM" src="https://github.com/styled-components/jest-styled-components/assets/30731236/f0d9495c-5ffb-4aaf-95dc-46e1a60e4b23">

**Note**: I tried to downgrade a few versions of `jest-styled-components` and `styled-components` but could not surpass this issue. Could you please share the possible fixes.

**Comment by khusharth** [comment]
@supminn Can you please share your jest configuration file / or a project link where this is reproducible?

**Comment by supminn** [comment]
Hi @khusharth 
Thanks for reaching out. Here's my package https://github.com/supminn/monorepo-lerna-demo/tree/master/packages/app-atoms (app-atoms).

I have created a react app using Vite. I tried to create unit tests using vitest. Since I have used styled-components, I was trying to test the styles using jest-styled-components.

Do let me know how I can fix this issue. Thanks.

**Comment by jalooc** [comment]
That's because Vitest by default does not expose `test`, `expect`, `beforeEach` etc. as globals, like jest does. You can make it easily work by changing that with a configuration: https://vitest.dev/config/#globals

However I'd love to see `jest-styled-components` enable an option to set up the _before_ hooks without needing to expose globals, because not having globals is preferable in general.

**Comment by me4502** [comment]
These expect calls would also hit issues without globals, https://github.com/styled-components/jest-styled-components/blob/main/src/utils.js#L72-L74

So it's more than just the hooks sadly

**Comment by guidsdo** [comment]
I found the solution in [@ggdaltoso's](https://github.com/React95/React95/pull/406) 

```
{
  "test": {
    "globals": true,
    "setupFiles": ["jest-styled-components"]
  }
}
```

**Comment by supminn** [comment]
> I found the solution in [@ggdaltoso's](https://github.com/React95/React95/pull/406)
> 
> ```
> {
>   "test": {
>     "globals": true,
>     "setupFiles": ["jest-styled-components"]
>   }
> }
> ```

This worked! Thank you soo much.
Closing this issue.
