### ISSUE TITLE
Matcher for checking existence of property

### ISSUE THREAD

**Issue by stephencroberts** [styled-components/jest-styled-components#47]
Would you consider a pull request that either adds a matcher or modifies `toHaveStyleRule` to check the existence of a css property rather than a value? I'm writing a series of tests to ensure a collection of components adhere to some standards, so I want to write a test similar to:

```
expect(tree).not.toHaveStyleRule('margin');
expect(tree).not.toHaveStyleRule('padding');
```

to ensure components don't have any margin defined. 

It could be added to `toHaveStyleRule` without a breaking change, but it might also make sense as just another matcher.

**Comment by MicheleBertoli** [comment]
This would be an interesting addition to the current matcher, thanks @stephencroberts.
Looking forward to receiving a PR.

**Comment by stephencroberts** [comment]
@MicheleBertoli Thanks for the quick response. I actually just discovered I can cover the use-case using a regular expression:

```javascript
expect(tree).not.toHaveStyleRule('margin', /.*/);
```

If anyone else would find a more specific matcher useful, I'd be happy to still do a PR.

**Comment by MicheleBertoli** [comment]
@stephencroberts unfortunately this trick doesn't seem to work.

The following test passes because it compares `/.*/`and `'4em'`.

```js
const Wrapper = styled.section`
  padding: 4em;
`

const tree = renderer.create(<Wrapper />).toJSON()
expect(tree).not.toHaveStyleRule('padding', /.*/)
```

**Comment by stephencroberts** [comment]
@MicheleBertoli Yes, I just realized this morning after upgrading to a newer version that regular expression matchers are no longer supported. Could we possibly add that back in? It solves a number of different use-cases for me. It was working in v3.0.2, not sure when it was removed.

**Comment by MicheleBertoli** [comment]
Sure @stephencroberts, v4.2.0 supports RegExp.
Thank you very much!
