### ISSUE TITLE
Sometimes getClassNames throws error

### ISSUE THREAD

**Issue by yanawaro** [styled-components/jest-styled-components#51]
I've been using some of my own code to test styles on styled-components v1 before, now migrating to v2 and came across this library. As far, Migrating test and I really like it. 👍  But I went into this issue.

With reference with this line of code in getClassNames function
https://github.com/styled-components/jest-styled-components/blob/master/src/toHaveStyleRule.js#L11

Using ```.find('[className]').first().prop('className')``` sometimes throw an error. It cannot find that node. 

![screen shot 2017-07-20 at 3 58 36 pm](https://user-images.githubusercontent.com/846906/28410697-a75dfbfe-6d68-11e7-80b4-253e2e00f48b.png)

For example in the test suite I send in the component to match styles like
```expect(wrapper.find('TabButtonGroup')).toHaveStyleRule('background-color', baseColors.capecod)```

I understand that we already sent in a wrapper to find something to retrieve styles. Why it would perform another to find children that contains classnames?

From my utility, I've using go get classnames from enzyme selectors by reading ```generatedClassName``` property in the component state.
Then it should get the classname by  ```received.getNode().state.generatedClassName```
I tried and it could get by using this code.

I test and the different is the getting by props as in the current codebase has combined classnames if there are overrides? May be is it for this benefit?

**Comment by MicheleBertoli** [comment]
Hello @yanawaro, any chances you could provide a non-working example? or the output of `wrapper.debug()`?
To me, it seems that the first `find` doesn't actually find anything in your case.

In general, performing a second `find` is not a problem.
For example, the following code works:

```js
const TabButtonGroup = styled.div`
  color: red;
`
const Autocomplete = () =>
  <div>
    <TabButtonGroup />
  </div>

const wrapper = mount(<Autocomplete />)
expect(wrapper.find(TabButtonGroup)).toHaveStyleRule('color', 'red')
```

Also, I tend to avoid using the internals whenever it's possible.

**Comment by yanawaro** [comment]
@MicheleBertoli from last comment, I prefer not using the internals too 👍 .  Let's see if this is a problem and how can we fix.

I think I found something. Not sure if it has something to do with using the styled-components overriding api.
And not sure if ```.find('[className]').first().prop('className')``` works in these situation.

Ex1: I ran this basic example which produces the same errors as above.

```js
const Component = () => (
  <div />
)
    
const Override = styled(Component)`
  display: none;
`

const wrapper = mount(<Override />)
expect(wrapper.find(Override)).toHaveStyleRule('display', 'none')
```

**When using ```wrapper.find(Override)``` like this, I expected it to get the styles of Override component**

Errors:
![screen shot 2017-07-20 at 8 16 29 pm](https://user-images.githubusercontent.com/846906/28419144-5b7256ac-6d88-11e7-9d50-1840367e8b75.png)
Debug (wrapper):
![screen shot 2017-07-20 at 8 17 08 pm](https://user-images.githubusercontent.com/846906/28419184-723fc6b2-6d88-11e7-83ca-16731e622a8f.png)

Ex-2: Modified the component to pass thru classnames

```js
const Component = ({className}) => (
  <div className={className} />
)
    
const Override = styled(Component)`
  display: none;
`

const wrapper = mount(<Override />)
expect(wrapper.find(Override)).toHaveStyleRule('display', 'none')
```

**And it passes!**
![screen shot 2017-07-20 at 8 22 18 pm](https://user-images.githubusercontent.com/846906/28419468-305a3916-6d89-11e7-96a0-d75ab26f9e79.png)

Ex-3: Having some styled-components inside, but not passing thru classnames
```js
const Base = styled.div`
  display: inline-block;
`

const Component = () => (
  <div/>
    <Base />
  <div/>
)
    
const Override = styled(Component)`
  display: none;
`

const wrapper = mount(<Override />)
expect(wrapper.find(Override)).toHaveStyleRule('display', 'none')
```

**It could find a component but wrong one!, and reads out the styles of the wrong element. (It gets the displays from <Base />)**

![screen shot 2017-07-20 at 8 28 05 pm](https://user-images.githubusercontent.com/846906/28419667-f6562062-6d89-11e7-909d-5644df92680a.png)

**It seems that it leads to selecting wrong elements and asserting wrong styles?**

**Comment by MicheleBertoli** [comment]
Thank you very much for the comment and the examples @yanawaro.

If you apply the `styled` function to a component that doesn't accept the `className` prop, no styles are applied to it. Therefore the test (1) doesn't pass, while the (2) passes. This is the expected behavior.
Maybe we can handle the case on the library side and show a better error message.

In the example (3) again the component doesn't accept any `className`, and the library tries to get the styles from the first element that has the prop. I agree this is not optimal, but it was an easy win to make it work transparently with Enzyme's `mount`. I'll think about it.

**Comment by MicheleBertoli** [comment]
Thank you very much for the comment and the examples @yanawaro.

If you apply the `styled` function to a component that doesn't accept the `className` prop, no styles are applied to it. Therefore the test (1) doesn't pass, while the (2) passes. This is the expected behavior.
I'm going to handle the case on the library side and show a better error message.

In the example (3) again the component doesn't accept any `className`, and the library tries to get the styles from the first element that has the prop. I agree this could work better, but it was an easy win to make it work transparently with Enzyme's `mount`, themes, etc.

**Comment by MicheleBertoli** [comment]
In v4.1.2, the example (1) now gives:

> Property not found: "display"

Thank you very much!

**Comment by yanawaro** [comment]
@MicheleBertoli Sorry for commenting on a close thread.

Thanks for you explanation! I now understand and agreed with behavior with passing thru / not passing thru classnames. Because if using the override api, should work on overriding other styled components. But creating our own components it's right to pass thru classname prop.

I've been trying to reproduce this error, It seems that I only happens in this situation. I don't know if you had encounter something like this.

```js
// this code is in a fully state component and exports as Suggest
const Root = styled.ul``
const Item = styled.li``
render (
  <Root show={isShow} className={this.props.className}>
    {suggests.length && suggests.map(suggest => <Item>{suggest}</Item>)}
  </Root>
)
```

Another component uses it with overriding as
```js
const SearchSuggest = styled(Suggest)`
  display: ${props => (props.show === true) ? 'block' : 'none'};
`
SearchSuggest.displayName = 'SearchSuggest'
```

If the suggest array is empty, from this debugging output, it seems it doesn't render ```<ul>``` element. So it cannot find it styles. (I tried to change ul to div, but it has noting to do.)
![screen shot 2017-07-21 at 12 59 30 pm](https://user-images.githubusercontent.com/846906/28451875-1a1e090c-6e1a-11e7-94f6-9471c29834b7.png)

Compare to if it has suggest items, debugging shows it has items, so it can find its style.
<img width="1082" alt="screen shot 2017-07-21 at 1 39 39 pm" src="https://user-images.githubusercontent.com/846906/28451923-5a9add0c-6e1a-11e7-8197-578862343e13.png">

Is this strange? or it maybe with my coding.

**Comment by MicheleBertoli** [comment]
This is weird, and I wouldn't expect it to happen - especially with `mount`.

Also, I tried to repro the issue with the code you provided:

```js
const Root = styled.ul``
const Item = styled.li``

class Suggest extends React.Component {
  render() {
    const { isShow, suggests } = this.props
    return (
      <Root show={isShow} className={this.props.className}>
        {suggests.length &&
          suggests.map(suggest =>
            <Item>
              {suggest}
            </Item>
          )}
      </Root>
    )
  }
}

const SearchSuggest = styled(Suggest)`
  display: ${props => (props.show === true ? 'block' : 'none')};
`
SearchSuggest.displayName = 'SearchSuggest'
```

And when I log the output of the debug function:

```js
console.log(mount(<SearchSuggest suggests={[]} />).debug())
```

I get this, which seems right.

```js
<SearchSuggest suggests={{...}}>
  <Suggest className="sc-htpNat irkcXP" suggests={{...}}>
    <styled.ul show={[undefined]} className="sc-htpNat irkcXP">
      <ul className="sc-htpNat irkcXP sc-bdVaJa bDWFJH" />
    </styled.ul>
  </Suggest>
</SearchSuggest>
```

Maybe the problem is somewhere else.

**Comment by yanawaro** [comment]
@MicheleBertoli Thanks for your help, I'll try to see further what went wrong. :joy:
