### ISSUE TITLE
toHaveStyleRule pseudo classes support

### ISSUE THREAD

**Issue by yanawaro** [styled-components/jest-styled-components#52]
I like using toHaveStyleRule more than using snapshots for testing. I was running tests that includes assertions of media queries. But found out that the code doesn't includes rules from media queries. So I modified to get it working adding a function to get it like

```js
// toHaveStyleRule.js
...
const getMediaRules = (ast, classNames) => {
  return ast.stylesheet.rules
    .filter(rule => rule.type === 'media')
    .map(rule => rule.rules)
    .reduce((a, b) => a.concat(b), [])
    .filter(rule => hasClassNames(classNames, rule.selectors))
}

...
// in toHaveStyleRule()
const mediaRules = getMediaRules(ast, classNames)
const rules = getRules(ast, classNames).concat(mediaRules)
```

I could get it up and running as for now, but a new problem arises. It combines the rules so ordering has effect. The last one is the one that will be matched. (The picture shows the same property rule but different media queries.)

![screen shot 2017-07-20 at 3 44 29 pm](https://user-images.githubusercontent.com/846906/28412219-a76e27f4-6d6d-11e7-8f13-7fe7e068c7d3.png)

Would it be better for testing media queries styles with an options api like
```js
expect(component).toHaveStyleRule('margin', '50px', {media: {'max-width': '768px'}})
```
and match style within rules of that media query only?
If interested and have any comments how the api should call, I will try to work on and submit PR. 👍

**Comment by MicheleBertoli** [comment]
This a pretty cool idea, thanks @yanawaro.

I like this signature:
```js
expect(component).toHaveStyleRule('margin', '50px', { media: { 'max-width': '768px' } })
```
And I'll be happy to review and merge a PR :)

**Comment by rsouthgate** [comment]
In the same vain it would be good to be able to query pseudo styles like :focus, :disabled, :readonly etc... to be generic would it make more sense to expect the signature to be:

```javascript 
expect(component).toHaveStyleRule('media(\'max-width\': \'768px\') { \'margin\'}', '50px')
```
or
```javascript
expect(component).toHaveStyleRule(':focus {\'margin\'}', '50px')
```
admittedly, not great readibility with all the escaped ticks... could the third arg be a generic selector instead of a media query?

**Comment by MicheleBertoli** [comment]
Oh yeah @rsouthgate, I like the third parameter because we can use it for different purposes.

For example: 
```js
expect(component).toHaveStyleRule('margin', '50px', { pseudo: 'hover' })
```

Or even combine them:
```js
expect(component).toHaveStyleRule('margin', '50px', { media: { 'max-width': '768px' }, pseudo: 'hover' })
```

**Comment by yanawaro** [comment]
@rsouthgate its possible, Need to add little more filters to get the pseudo rules for that classname only :yum:.

@MicheleBertoli If adding support psuedo rules, we need to modified the ```hasClassNames``` function to support or just define something new like ```hasPseudo``` due to the pseudo styles when parsed it looks like this.

![screen shot 2017-07-25 at 12 15 58 am](https://user-images.githubusercontent.com/846906/28535643-4e0c81dc-70cf-11e7-9ffd-9ee002d9ebe2.png)

**Comment by MicheleBertoli** [comment]
@yanawaro oh yeah, or even something like:

```js
const hasClassNames = (classNames, selectors, options) =>
  classNames.some(className => selectors.includes(
    `.${className}${options.pseudo ? `:${options.pseudo}` : ''}`
  )
)
```

**Comment by mbasso** [comment]
@MicheleBertoli I've developed a feature like that in [styled-components-test-utils](https://github.com/mbasso/styled-components-test-utils#tohavestylerule). If you want to take a look, I think that you might find some interesting code to do this 😄

**Comment by MicheleBertoli** [comment]
Nice, thanks @mbasso.
Unfortunately, you forked an older version of the matcher (which has been recently rewritten) so I don't believe we'll be able to reuse the code.

Also, it's a shame you didn't reach out before investing time in your repo, we could have built something great together : )
Users have now to packages with some overlapping features and different APIs, which is going to generate confusion.

**Comment by mbasso** [comment]
You're right, if you agree we can organize us too build something together. It would be great to have a single and complete library to test styled-components, it might help a lot of people.
If you want to do that, please let me know :)

**Comment by MicheleBertoli** [comment]
This is no one's fault, there's always time to build something better together :)
Let's discuss this in a separate [issue](https://github.com/mbasso/styled-components-test-utils/issues/2).

**Comment by MicheleBertoli** [comment]
This is no one's fault, there's always time to build something better together :)
Let's discuss it in a separate [issue](https://github.com/mbasso/styled-components-test-utils/issues/2).

**Comment by MicheleBertoli** [comment]
The media query support has been shipped, thanks to @yanawaro.
Please let me know if you'd like to work on the pseudo classes support as well.

**Comment by yanawaro** [comment]
@MicheleBertoli Sure, I can submit a PR for enhancing with pseudo classes as soon as possible.

**Comment by MicheleBertoli** [comment]
Yay, thanks @yanawaro.
