### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by TAQ2** [styled-components/jest-styled-components#54]
Hello, thanks for reading.

Just wondering if you have a changelog? I couldn't find one but perhaps you keep it somewhere I have not looked.

Thanks!

**Comment by MicheleBertoli** [comment]
Thanks for your question, @TAQ2.
At the moment there's no changelog.
You should be able to find all the information in the commit messages (I know it's not ideal), and if you have any more questions please ask.

I'm following semantic versioning and the biggest breaking change we introduced so far was in v4, when we removed the `toMatchStyledComponentsSnapshot` matcher and replaced the hashed class names with placeholders.

I'm going to leave this open until we have one :)

**Comment by MicheleBertoli** [comment]
[Here we go](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md).
Thanks @TAQ2.

**Comment by TAQ2** [comment]
Wow a speedy reply and result. Thanks very much!!
