### ISSUE TITLE
Is toMatchStyledComponentsSnapshot now deprecated?

### ISSUE THREAD

**Issue by joetidee** [styled-components/jest-styled-components#57]
I have just updated from version 3 to the latest, so is the function `toMatchStyledComponentsSnapshot` now deprecated?

**Comment by MicheleBertoli** [comment]
Oh yes @joetidee, please see [here](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#400---2017-07-15).
The `toMatchStyledComponentsSnapshot` matcher has been removed, and you can just use the regular `toMatchSnapshot` now.
