### ISSUE TITLE
Formating removed when updating snapshots

### ISSUE THREAD

**Issue by newswim** [styled-components/jest-styled-components#58]
Hi @MicheleBertoli 

I'm sorry this might not the fault of this project, but the names `jest` and `styled-components` have been giving me grief and I hoped you had maybe see this happening.

It seems to have something to do with the environment that the tests are running in. I'm using yarn, but encountering issues where a space character is getting removed:

<img width="650" alt="screen shot 2017-07-28 at 6 05 10 pm" src="https://user-images.githubusercontent.com/6667096/28739293-6b147904-73bf-11e7-84f3-25b3c2f5c0f1.png">

Same goes for urls that would be passed to a component. I can provide more details, just wondering if there's anything familiar that you might know is going on. Appreciate this project a lot!

**Comment by MicheleBertoli** [comment]
Hello @newswim, this seems related to #44.

Are you using [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components)? 
If the answer is yes, please check out this [PR](https://github.com/lgraziani2712/codimo/pull/45) and see if it solves your problem as well.

**Comment by newswim** [comment]
Hey thanks for that link! I'm not using the babel-plugin on this project, though.

I had some luck after upgrading several eslint dependencies. There's still an issue where mock data is subbing a `%20` rather than a space, and leading spaces for css rules with multiple arguments is getting stripped, but at least Travis is producing the same snapshots.

I would rather the generated snapshots retain those spaces, so the search is still on. Thanks again.

**Comment by MicheleBertoli** [comment]
I see, the important thing is that snapshots are consistent across the different environments.
Please let me know if you need more help, and I'll be happy to know the root cause of the problem in case you find it.
Thanks!

**Comment by nezed** [comment]
Had the same issue because i've made snapshots using `styled-components@2.0.1`, but CI installs `styled-components@2.1.2`.
Solved by upgrading `styled-components` and regenerating snapshots.
