### ISSUE TITLE
expect.addSnapshotSerializer is not a function

### ISSUE THREAD

**Issue by luftywiranda13** [styled-components/jest-styled-components#7]
![screen shot 2017-04-24 at 11 35 59](https://cloud.githubusercontent.com/assets/22868432/25322592/8ab2f51a-28e2-11e7-932f-0bf2abb642e5.png)

I got that when I run the test on top of a **CRA** project.

This is my test suit:
![screen shot 2017-04-24 at 11 36 22](https://cloud.githubusercontent.com/assets/22868432/25322610/a75e5808-28e2-11e7-99ed-e81ab42ac0f8.png)

**Comment by MicheleBertoli** [comment]
Hello @luftywiranda13,
the [addSnapshotSerializer](https://github.com/facebook/jest/blob/996ba5d4f1e493e18f7dbc4bbe37a09cd271276f/CHANGELOG.md#jest-1900) function works with Jest 19+.
I assume you are using an earlier version, right?

**Comment by luftywiranda13** [comment]
@MicheleBertoli the latest CRA uses **jest v18.x.x**

I think we can't easily upgrade jest in CRA

**Comment by MicheleBertoli** [comment]
You are [right](https://twitter.com/kentcdodds/status/856720119841439744) @luftywiranda13, you just need to wait for the [next version](https://github.com/facebookincubator/create-react-app/issues/1604) of CRA.
