### ISSUE TITLE
CSS classes duplicated and inserted inside tags with Jest 21

### ISSUE THREAD

**Issue by dgcoffman** [styled-components/jest-styled-components#73]
given

``` javascript
import React from 'react';
import styled from 'styled-components';
import { mount } from 'enzyme';
import toJson from 'enzyme-to-json';
import 'jest-styled-components';

const Text = styled.span`color: red;`;

test('renders', () => {
  expect(toJson(mount(<Text />))).toMatchSnapshot();
});
```

Jest 20 produces snapshot
``` javascript
exports[`renders 1`] = `
.c0 {
  color: red;
}

<Text-test__Text>
  <span
    className="c0"
  />
</Text-test__Text>
`;
```

Jest 21 produces snapshot

``` javascript
exports[`renders 1`] = `
.c0 {
  color: red;
}

<Text-test__Text>
  .c0 {
  color: red;
}

<span
    className="c0"
  />
</Text-test__Text>
`;
```

**Comment by MicheleBertoli** [comment]
Thank you very much @dgcoffman, this is my next priority.
Fyi, yesterday we pushed a new [version](https://github.com/styled-components/jest-styled-components/blob/ea0f68e32e12b0eb2f17c90032608a38a48c2589/CHANGELOG.md#450---2017-09-05) of the package that makes the `toHaveStyleRule` matcher support v21.
PRs are also welcome :)

**Comment by MicheleBertoli** [comment]
[v4.6.0](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#460---2017-09-09) supports Jest 21.
Thank you very much!
