### ISSUE TITLE
CSS parser returns different values for matching

### ISSUE THREAD

**Issue by yanawaro** [styled-components/jest-styled-components#74]
@MicheleBertoli 😃 

I encounter that I have 2 projects that installs the same jest-styled-components package but when running the same exact test the CSS parser returns different strings when matching rules.

This is what it should be expected. (Like [test)](https://github.com/styled-components/jest-styled-components/blob/master/test/toHaveStyleRule.spec.js#L152)
<img width="605" alt="screen shot 2017-09-07 at 2 49 03 pm" src="https://user-images.githubusercontent.com/846906/30152407-348254c2-93dd-11e7-85c3-f22d31432018.png">

Oops! This is not right, The space disappears.
<img width="660" alt="screen shot 2017-09-07 at 2 49 21 pm" src="https://user-images.githubusercontent.com/846906/30152416-3a17b24c-93dd-11e7-824a-26b783f86956.png">

I inspect that the css parser version is the same. ```"version": "2.2.1"```
What could be the causes of this? Or how should we handle it? 😂

**Comment by MicheleBertoli** [comment]
Hello @yanawaro, I'm happy to hear from you.
Are you using the `babel-plugin-styled-components` in one of those projects?
We had a similar issue #44 in the past.
Thanks!

**Comment by yanawaro** [comment]
@MicheleBertoli I've been a bit busy for a while.

Nope, I didn't use ```babel-plugin-styled-components``` in any of these. So I exclude some other babels plugins but doesn't solve.

**Comment by yanawaro** [comment]
@MicheleBertoli It was indeed because of ```stylis``` version. The version that causes tests to failed was 3.2.15 I revert to use 3.2.4. Just make it work for my work now is ok.

It might be an issue for users installing ```styled-components``` and get newer versions of ```stylis``` and use ```jest-styled-components``` for testing. Should we concern?

**Comment by MicheleBertoli** [comment]
I see, thank you very much @yanawaro.
I'm happy you found the root cause and a solution.
It seems like an edge case to me and I don't think we should do something about it at the moment.
