### ISSUE TITLE
Question: injectGlobal

### ISSUE THREAD

**Issue by mwatt** [styled-components/jest-styled-components#83]
Hi!

Is there a way to test styles applied by injectGlobal?

Thanks!

**Comment by MicheleBertoli** [comment]
Hello @mwatt, thanks for your question.
Using `injectGlobal` is discouraged and it should be used only for the fonts and/or styling body.
Can you please elaborate further and provide a use-case?
Thanks!

**Comment by mwatt** [comment]
Hello @MicheleBertoli,

This is my main.js file. I'd like to have tests to check these styles are applied to the page where my app is gonna live.

```javascript
import React from 'react'
import ReactDOM from 'react-dom'
import { injectGlobal } from 'styled-components';
import RootComponent from './app/Root'

injectGlobal`
  html, body, #app {
    height:100%;
    margin:0;
  }
`;

ReactDOM.render(<RootComponent />, document.getElementById('app'));
```

Thanks!

**Comment by MicheleBertoli** [comment]
Thank you very much for providing more details @mwatt.
I don't think you should test whether `injectGlobal` works because it's already tested in the SC repo.

However, you could do something like:
```js
test('injectGlobal', () => {
  injectGlobal`
    html, body, #app {
      height:100%;
      margin:0;
    }
  `
  const style = document.querySelector('style').innerHTML
  expect(style).toContain('html,body,#app{height:100%;margin:0;}')
})

```
