### ISSUE TITLE
Feature Request: test utilities e.g. `toHaveStyleRule` of the jest-styled-component should not tied to `jest`

### ISSUE THREAD

**Issue by wood1986** [styled-components/jest-styled-components#84]
I am not using jest as the test and assertion framework to test the react component. Because of using toHaveStyleRule, I have to install jest

**Comment by MicheleBertoli** [comment]
Hello @wood1986, thanks for opening this issue.
The package is called **jest**-styled-components therefore it's been built with Jest in mind.
Which other test and assertion frameworks would you like it to support?

**Comment by wood1986** [comment]
jasmine

**Comment by mwatt** [comment]
mocha

**Comment by MicheleBertoli** [comment]
chai (https://github.com/styled-components/jest-styled-components/issues/71)

**Comment by madiodio** [comment]
For those not using Jest, check out [styled-components-test-utils](https://github.com/mbasso/styled-components-test-utils). It is compatible with expect, chai and jasmine.

**Comment by MicheleBertoli** [comment]
We started [talking about](https://github.com/mbasso/styled-components-test-utils/issues/2) creating a "universal" utility to test Styled Components.
However, at the moment I prefer this package to do one thing well and stick to Jest.
Thank you very much everyone.
