### ISSUE TITLE
toHaveStyleRule should intelligently ignore spaces

### ISSUE THREAD

**Issue by jmjpro** [styled-components/jest-styled-components#89]
I defined my styles using colors like rgba(101, 45, 144, 1). toHaveStyleRule() fails to match because styled-components seems to be removing spaces from the color value like this rgba(101,45,144,1). Either styled-components shouldn't remove the spaces, or toHaveStyleRule() should also ignore the spaces when comparing.

**Comment by MicheleBertoli** [comment]
Hello @jmjpro, thanks for opening the issue.

I can't repro the problem in this repo.
For example, the following test works as expected in `test/toHaveStyleRule.spec.js`:
```js
test('ignore spaces', () => {
  const Wrapper = styled.section`
    color: rgba(101, 45, 144, 1);
  `

  toHaveStyleRule(<Wrapper />, 'color', 'rgba(101, 45, 144, 1)')
})
```

However, this is not the first time we hear about a similar problem.
Can you please give us more info about your setup or provide a non-working example?

**Comment by MicheleBertoli** [comment]
Ping @jmjpro : )
