### ISSUE TITLE
Problems with testEnvironment "node"

### ISSUE THREAD

**Issue by joseaplwork** [styled-components/jest-styled-components#9]
I'm barerly sure that I'm not the only one who is using jest with the default test environment which is "jsdom" for [jest](https://facebook.github.io/jest/docs/configuration.html#testenvironment-string).

So I love this library, it works very well with the `v2.0` but changing my `testEnvironment` to `node` just broke my tests. Because in my project I have access to the DOM global variables and the `testEnvironment:  jsdom` handles it very good.

So I would like to keep the consistency in my tests and the `jsdom` test environment instead of adding complex global definitions.

Is there a workaround for this?

**Comment by MicheleBertoli** [comment]
Thanks @joseaplwork for opening the issue.
I'm going to close this in favor of #2 (which I just reopened).
Also, facebook/jest#3156 introduces the multi-project support which makes it possible to run Jest with different configurations.
