### ISSUE TITLE
how to avoid typescript error when configuring jest-styled-components for all tests

### ISSUE THREAD

**Issue by jmjpro** [styled-components/jest-styled-components#90]
When I import jest-styled-components for all tests via the setupTestFrameworkScriptFile jest configuration option, I get a warning on every line in every that calls toHaveStyleRule():

`Property 'toHaveStyleRule' does not exist on type 'Matchers<void>'`

and tsc build fails

Is there a way to fix this?

**Comment by MicheleBertoli** [comment]
Hello @jmjpro, thanks for opening the issue.
Any hint here @kevcenteno @HenrikFricke @jiayihu?
Thank you very much!

**Comment by jmjpro** [comment]
I updated the issue title and description above as the build actually fails.

**Comment by kevcenteno** [comment]
@jmjpro Can you put up an example project that reproduces this issue?

**Comment by jiayihu** [comment]
I think TS can't know the types of the package because it's never imported explicitly. Did you try with a `index.d.ts` definition file where you import the package? `import * as jestStyledC from 'jest-styled-components'`?

**Comment by MicheleBertoli** [comment]
Ping @jmjpro : )
