### ISSUE TITLE
react 15.4.1 is not working with jest styled component

### ISSUE THREAD

**Issue by rahul-network** [styled-components/jest-styled-components#91]
When we try to use that 
Error msg : " Cannot read property 'ReactCurrentOwner' of undefined"

**Comment by MicheleBertoli** [comment]
Hello @rahul-network, we updated the package to support React 16 in [v4.7.0](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#470---2017-09-30).

I strongly suggest upgrading React in your project.
However, if that's not possible you could try using an older version of this package, e.g. `yarn add --dev jest-styled-components@4.6.0`.
