### ISSUE TITLE
Different output locally and on CI with enzyme render method

### ISSUE THREAD

**Issue by okonet** [styled-components/jest-styled-components#92]
I'm not sure what's causing this but I have a different output on CI which fails my tests.

Here is an output I'm getting on CI (Bitbucket's pipelines):

```
  ● MenuItem › should render LI element
    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -11,7 +11,7 @@
     .c0:hover {
       background-color: rgba(0,0,0,.05);
     }
     
     <li
    -  class="sc-bwzfXH c0"
    +  class="c0"
     />
```

and test looks like 

```
  it('should render LI element', () => {
    const component = render(<MenuItem />);
    expect(component).toMatchSnapshot();
  });
```

So it looks like locally SC create an additional `sc-` class but on CI this isn't happening.

cc @mxstbr

**Comment by okonet** [comment]
This seems to be fixed after upgrading to v4.9.0

**Comment by MicheleBertoli** [comment]
I'm glad to see the latest version fixes the issue.
Thank you very much, @okonet.

**Comment by okonet** [comment]
Looks like I'm still experiencing some weirdness with it...

Depending on what order I `import` JS modules in my file I get different snapshots for the component.

So this change:

```diff
--- a/src/content/app/components/ui/InputFilterList/InputFilterList.jsx
+++ b/src/content/app/components/ui/InputFilterList/InputFilterList.jsx
@@ -1,8 +1,8 @@
 import React, { PropTypes } from 'react';
-import { Box } from 'grid-styled';
 import { DeluxeTextInput } from '../DeluxeTextInput';
 import { Menu, MenuItem, MenuItemDivider } from '../Menu';
 import { SelectableList, SelectableListSection } from '../SelectableList';
+import { Box } from 'grid-styled';
 
 const SelectableMenu = SelectableListSection('div');
```

Produces following snapshot failure:

```diff
    - Snapshot
    + Received
    
    @@ -1,5 +1,10 @@
    +.c0 {
    +  box-sizing: border-box;
    +  margin: 8px;
    +}
    +
     <InputFilterList
       autoFocus={false}
       filterKey="label"
       filterTerm=""
       itemGroups={Array []}
    @@ -12,15 +17,15 @@
       >
         <Box
           m={1}
         >
           <Base
    -        className="sc-bdVaJa jnaVga"
    +        className="c0"
             m={1}
           >
             <div
    -          className="sc-bdVaJa jnaVga"
    +          className="c0"
               is={null}
             >
               <DeluxeTextInput
                 autoFocus={false}
                 className=""
```

**Comment by okonet** [comment]
And on CI it's the other way around. I'm confused how is this even possible 🤔

**Comment by okonet** [comment]
So it looks like an ongoing issue with how dependencies are require (in which order) but what I can't understand now is why different ends causing it.

**Comment by okonet** [comment]
@MicheleBertoli any pointers where to look?

**Comment by MicheleBertoli** [comment]
I'm sorry to hear the problem persists, @okonet.
This is a pretty weird and interesting issue.

The problem with third-party components is [known](https://github.com/styled-components/jest-styled-components/issues/81#issuecomment-334990026) - and there isn't much we can do at the moment unfortunately.
However, I don't really see how the behaviour should be different on local VS CI or, even worse, by changing the order of the required packages.

Would you be able to provide a minimal non-working example so that I can debug the issue?
I'll be more than happy to help.

**Comment by MicheleBertoli** [comment]
Ping @okonet, are you still experiencing the issue?
Thank you very much!
