### ISSUE TITLE
missing '}' when using polished's placeholder and styled-component's Theme

### ISSUE THREAD

**Issue by BernardoMariano** [styled-components/jest-styled-components#93]
This took me a while to figure out. I'm trying to style the `::placeholder` pseudo-element of my input text using Polished's [placeholder](https://polished.js.org/docs/#placeholder) helper:

```javascript
it('should correctly render an <Input /> with styled placeholder', () => {
    const Input = styled.input`
        ${ ({ theme }) => {
            return `
                color: #4a4a4a;
                ${ placeholder({ color: theme.common.placeholderColor }) }
            `
        } }
    `

    const tree = renderer.create(
        <ThemeProvider theme={ theme }>
            <Input />
        </ThemeProvider>
    ).toJSON()

    expect(tree).toHaveStyleRule('color', '#4a4a4a') // should pass seamlessly
})
```

Although in the browser it worked perfectly, tests are failing with an unreasonable `missing '}'`:

![image](https://user-images.githubusercontent.com/3067157/32609605-58ed5e7e-c547-11e7-8240-2a4a002c104a.png)

And for my surprise, the issue was with that function receiving my `theme`, and removing that, it worked:

```javascript
it('should correctly render an <Input /> with styled placeholder', () => {
    const Input = styled.input`
        color: #4a4a4a;
        ${ placeholder({ color: '#d2d2d2' }) } // hardcoded hex, no more theme :(
    `

    const tree = renderer.create(<Input />).toJSON()

    expect(tree).toHaveStyleRule('color', '#4a4a4a')
})
```

![image](https://user-images.githubusercontent.com/3067157/32610309-86172ad6-c549-11e7-80a7-945751b17f11.png)

Nonetheless, thank you for your time spent on this Jest utility! It's been of great help 👍

**Comment by MicheleBertoli** [comment]
Thank you very much for opening the issue, @BernardoMariano.

So, the result of this:
```js
${ ({ theme }) => {
  return `
    color: #4a4a4a;
    ${ placeholder({ color: theme.common.placeholderColor }) }
  `
} }
```

Seems to be:
```css
.innGvt{color: #4a4a4a;[object Object];}
```

And that's why the CSS parser fails.

Also, the code above [seems not to work](https://codesandbox.io/s/6jjy8v2o0n) in the browser as well.

<img width="165" alt="screen shot 2017-11-10 at 5 45 48 pm" src="https://user-images.githubusercontent.com/1308971/32671374-18d148ca-c63f-11e7-9704-fc0eddbda914.png">

The following works:

```js
const Input = styled.input`
  color: #4a4a4a;
  ${ ({ theme }) => placeholder({ color: theme.common.placeholderColor }) }
`
```

I hope this helps.

**Comment by brycepj** [comment]
I'm having what seems like the same issue.

`undefined:21:86: missing '}' `

I can't get any version of the following to run, without seeing the above ☝️ error, although they *do* work properly in the browser.

```javascript
export const Label = styled.div`
  width: ${({ plain }) => plain && 'width: 50%'};                                                                                                                                                              
  &:first-child {                                                                                                                                                                                
    ${({ plain }) => !plain && 'text-align: right'};
 `;
```
This works, however: 

```javascript
export const Label = styled.div`
  width: ${({ plain }) => {
     return !plain ? '50%' : 'auto';
   }};
   &:first-child {
      text-align: ${({ plain }) => {
        return !plain ? 'right' : 'left';
   }};
}
`;
```

I did, however, notice that if I removed the `&:first-child` styles, the error goes away.

**Comment by greypants** [comment]
This seems to be the answer: https://www.styled-components.com/docs/api#css
 
Details on this issue: here: https://github.com/styled-components/jest-styled-components/issues/97#issuecomment-364169127
