### ISSUE TITLE
Testing Helper Functions That Use CSS

### ISSUE THREAD

**Issue by Undistraction** [styled-components/jest-styled-components#94]
When testing utils that use `css` to return styles ready for interpolation you can currently do this:

```
describe('aboveWidth', () => {
  it('returns the correct media query', () => {
    const result = query.aboveWidth(
      'small',
      `
      background-color: GhostWhite;
    `
    );
    expect(result).toMatchSnapshot();
  });
});
```

However, it would be much clearer if you could do this:

```
describe('aboveWidth', () => {
  it('returns the correct media query', () => {
   const expected = `
   @media screen and (minWidth: 60em) {
       background-color: GhostWhite;
   }
   `;

    const result = query.aboveWidth(
      'small',
      `
      background-color: GhostWhite;
    `
    );
    expect(result).toMatchCSS(expected);
  });
});
```

It looks like `./utils/stringifyRules` would to do the trick, but it isn't exposed.

[Edit] I'm doing this in my tests, using `normalizeCSS` to ensure both the styles I declare and the styles returned from the helper are formatted the same. I'm looking for a better way to do this:

```
import mq from '../index';
import Stylis from 'stylis';
import 'jest-styled-components';

import { css } from 'styled-components';

const stylis = new Stylis({
  global: false,
  cascade: true,
  keyframe: false,
  prefix: true,
  compress: false,
  semicolon: true,
});

const normalizeCSS = value => {
  if (Array.isArray(value)) value = value.join(` `);
  const flatCSS = value.replace(/^\s*\/\/.*$/gm, ''); // replace JS comments
  return stylis('', flatCSS);
};

describe('aboveWidth', () => {
  it('returns the correct media query', () => {
    const expected = `
      @media screen and (min-width: 25em) {
        background-color: GhostWhite;
      }`;

    const result = mq.aboveWidth(
      'small',
      `
      background-color: GhostWhite
    `
    );
    expect(normalizeCSS(result)).toEqual(normalizeCSS(expected));
  });
});
```

**Comment by MicheleBertoli** [comment]
Hello @Undistraction, thanks for opening this issue.
I'm not sure I understand the use case, and I don't think it's related to this package nor to the Styled Components.

In general, one of the main benefits Snapshot Testing provides is letting you avoid thinking about the expected value and keeping it in sync with the output.
So, you replace `.toEqual(normalizeCSS(expected))` to `.toMatchSnapshot()` and once the first snapshot is right you can make sure the output doesn't change unexpectedly.

**Comment by Undistraction** [comment]
The problem with using snapshots for this are:

1. The contents of the snapshot is very hard to read because if there are interpolations, it is a flattened array, potentially quite a complex one.

2. The tests no longer function as documentation because you cannot see what the test is supposed to output. Yes you could look at the snapshot, but it is hard to read.

Can understand using snapshots for react components, because the snapshot acts as a flag that your refactoring has changed what is rendered. The rendered item isn't really part of the documentation. Here, the expected output is the documentation. The result of hitting `css` isn't rendering a component, but a data object.

I don't know what the answer is, but I think it's worthy of further discussion.

**Comment by MicheleBertoli** [comment]
Hello @Undistraction, thanks for providing additional information.
I think that in order to understand your problem for real, I need to see your code (e.g. I have no idea what the `mq` function returns).

However, I'm a huge fan of snapshots and I strongly believe they work very well for any kind of output (not just React components).
Also, I think snapshots are very effective in code reviews and I often use them as documentation.

That said, I suggest you give a look at the Jest custom [matchers](https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers) and [serializers](https://facebook.github.io/jest/docs/en/expect.html#expectaddsnapshotserializerserializer) documentation.
That might help in finding a solution to your problem.

**Comment by Undistraction** [comment]
@MicheleBertoli Thanks. I think part of the problem was that I was returning a flattened interpolation, but I've realised I can return an object instead which makes the snapshot a lot more readable. I'm trying to hack together what I'm after and if I think it's useful I'll add it here.

**Comment by Undistraction** [comment]
@MicheleBertoli OK. I think I'm a little clearer on what I need. Hopefully this will make more sense:

At present jest-styled-components covers two situations really well where it comes to snapshots - if the result is a component (in which case you can call `toJSON` on it and it looks nice in the snapshot), or with functions that return objects (for example the mixin functions in Polish) which again look nice in the snapshot. 

However, there are times when it is too complex to return an object from function (in my case because the function is a tagged template and can receive any valid css. To convert this arbitrary input to a clean object to return is too complex. Because I need to support interpolations within the css, I end up with a flat array that looks like this when output to a snapshot:

```
exports[`aboveWidth returns the correct media query 1`] = `
Array [
  "
      @media ",
  "screen",
  " and ",
  "(min-width: 25em)",
  " {
        ",
  "
        background-color: ",
  [Function],
  ";
      ",
  ";
      }
    ",
]
`;
```

As you can see, this is really hard to read and understand (and some of my snapshots will be much more complex. So what I'm asking for is help with testing a helper function that returns this kind of flattened array. I hacked together a function to flatten this interpolation to a string to make it more readable:
```
import { compose, trim } from 'ramda';
import Stylis from 'stylis';

const stylis = new Stylis({
  global: false,
  cascade: true,
  keyframe: false,
  prefix: true,
  compress: false,
  semicolon: true,
});

const stringifyRules = rules => {
  const flatCSS = rules.join('').replace(/^\s*\/\/.*$/gm, '');
  return stylis('', flatCSS);
};

const collapseSpaces = s => s.replace(/\s\s+/g, ' ');

const removeBlankLines = s => s.replace(/^\s*\n/gm, '');

export default rules => {
  if (Array.isArray(rules)) return stringifyRules(rules);
  return compose(removeBlankLines, collapseSpaces, trim)(rules);
};
```

Which I can then use with: 
```
expect(toCSS(result)).toMatchSnapshot();
```

Which gives me a snapshot that looks like this:
```
exports[`aboveWidth returns the correct media query 1`] = `"@media screen and (min-width:25em){background-color:function (props){return:'GhostWhite';}}"`;
```

Which is better, but still not ideal.

I hope this makes some kind of sense.

**Comment by MicheleBertoli** [comment]
Thank you very much, @Undistraction. 
Now the problem is clearer: you want the output of [stringifyRules](https://github.com/styled-components/styled-components/blob/master/src/utils/stringifyRules.js).

Would something like this work for your use case?
(Assuming it's hidden into a custom serializer)

```js
import { css } from 'styled-components'
import stringifyRules from 'styled-components/lib/utils/stringifyRules'

test('css', () => {
  const complexMixin = css`
    color: ${props => (props.whiteColor ? 'white' : 'black')};
  `

  expect(stringifyRules(complexMixin)).toMatchSnapshot()
})
```

```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`css 1`] = `"color: function (props){return props.whiteColor ? 'white' : 'black';}"`;
```

**Comment by Undistraction** [comment]
@MicheleBertoli Yes. Exactly.  

I have this in a serializer which makes the tests nice and clean. You can see the serializer [here](https://github.com/Undistraction/styled-mq/blob/master/src/__tests__/helpers/cssSerialiser.js).
