### ISSUE TITLE
Support for portals

### ISSUE THREAD

**Issue by alansouzati** [styled-components/jest-styled-components#96]
I don't think this is a bug, but I'm creating an issue to see if the styled-components experts can help me testing my component that is a React 16 Portal and uses jest + styled components.

Right now my test looks like this:

```javascript
describe('Drop', () => {
  beforeEach(() => {
    // make sure to remove all body children
    document.body.innerHTML = '';
    document.body.appendChild(document.createElement('div'));
  });

  test('mounts', () => {
    mount(
      <Drop>
        <div id='drop-node'>
          this is a test
        </div>
      </Drop>, {
        attachTo: document.body.firstChild,
      }
    );
    expect(document.getElementById('drop-node')).toMatchSnapshot();
  });
});
```

You can notice that I don't use the return of `mount` since the React portal will render the element in another container. My snapshot looks like this:

```json
exports[`Drop mounts 1`] = `
<div
  id="drop-node"
>
  this is a test
</div>
`;
```

So far, so good. But I want to include the styles from styled components in the snapshot. `jest-styled-components` works fine when there is no portal involved but I don't think there is a solution today that will make testing SC + React Portals easier.

In the meantime I'm adding the following to include the test for styles:

```javascript
expect(
  cssbeautify(document.getElementsByTagName('style')[0].innerHTML, {
    indent: '  ',
  })
).toMatchSnapshot();
```

Any thoughts on this?

**Comment by MicheleBertoli** [comment]
Hello @alansouzati, thanks for opening this issue.
I'm not sure why you are using Enzyme's attachTo, and why you decided not to generate the snapshot from the wrapper.
Although the `Drop` component uses a React portal, the following test and snapshot look right:

```js
const Drop = ({ children }) =>
  ReactDOM.createPortal(children, document.createElement('div'))

const Styled = styled.div`
  color: red;
`

test('Drop', () => {
  const wrapper = mount(
    <Drop>
      <Styled id="drop-node">this is a test</Styled>
    </Drop>
  )
  expect(wrapper).toMatchSnapshot()
})
```

```js

exports[`Drop 1`] = `
.c0 {
  color: red;
}

<Drop>
  <styled.div
    id="drop-node"
  >
    <div
      className="c0"
      id="drop-node"
    >
      this is a test
    </div>
  </styled.div>
</Drop>
`;
```

I hope this helps.
Feel free to reopen the issue with more information, in case the problem is not solved for your use case.
